<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>4&nbsp; Güven Aralıkları ve Hipotez Testleri – R ile İstatistiğe Giriş ve Veri Dönüşümü</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./veri_donusum.html" rel="next">
<link href="./dagilim.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./temel_istatistik.html">Temel İstatistik</a></li><li class="breadcrumb-item"><a href="./hipotez.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Güven Aralıkları ve Hipotez Testleri</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R ile İstatistiğe Giriş ve Veri Dönüşümü</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/cetinservet/veritemizleme" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-ile-İstatistiğe-Giriş-ve-Veri-Dönüşümü.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-ile-İstatistiğe-Giriş-ve-Veri-Dönüşümü.docx">
              <i class="bi bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
</div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Önsöz</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Giriş</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./temel_istatistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Temel İstatistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_tipleri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">İstatistikte Veri Tipleri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ozet_istatistikler.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Merkezi Eğilim ve Yayılım Ölçüleri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dagilim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Dağılım Türleri ve Merkezi Limit Teoremi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hipotez.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Güven Aralıkları ve Hipotez Testleri</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./veri_donusum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Veri Dönüşümleri</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_manipulasyonu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Veri Manipülasyonu</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_temizleme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Veri Temizleme</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referanslar</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">İçindekiler</h2>
   
  <ul>
<li>
<a href="#g%C3%BCven-aral%C4%B1%C4%9F%C4%B1-confidence-interval---ci" id="toc-güven-aralığı-confidence-interval---ci" class="nav-link active" data-scroll-target="#g%C3%BCven-aral%C4%B1%C4%9F%C4%B1-confidence-interval---ci"><span class="header-section-number">4.1</span> Güven Aralığı (Confidence Interval - CI)</a>
  <ul class="collapse">
<li><a href="#pop%C3%BClasyon-standart-sapmas%C4%B1n%C4%B1-biliniyorsa-z.test-fonksiyonu" id="toc-popülasyon-standart-sapmasını-biliniyorsa-z.test-fonksiyonu" class="nav-link" data-scroll-target="#pop%C3%BClasyon-standart-sapmas%C4%B1n%C4%B1-biliniyorsa-z.test-fonksiyonu"><span class="header-section-number">4.1.1</span> Popülasyon Standart Sapmasını Biliniyorsa: <code>z.test()</code> Fonksiyonu</a></li>
  <li><a href="#pop%C3%BClasyon-standart-sapmas%C4%B1n%C4%B1-bilinmiyorsa-t.test-fonksiyonu" id="toc-popülasyon-standart-sapmasını-bilinmiyorsa-t.test-fonksiyonu" class="nav-link" data-scroll-target="#pop%C3%BClasyon-standart-sapmas%C4%B1n%C4%B1-bilinmiyorsa-t.test-fonksiyonu"><span class="header-section-number">4.1.2</span> Popülasyon Standart Sapmasını Bilinmiyorsa: <code>t.test()</code> Fonksiyonu</a></li>
  </ul>
</li>
  <li>
<a href="#hipotez-testleri-hypothesis-tests" id="toc-hipotez-testleri-hypothesis-tests" class="nav-link" data-scroll-target="#hipotez-testleri-hypothesis-tests"><span class="header-section-number">4.2</span> Hipotez Testleri (Hypothesis Tests)</a>
  <ul class="collapse">
<li><a href="#ortalamalar-i%C3%A7in-hipotez-testleri-hypothesis-tests-for-means" id="toc-ortalamalar-için-hipotez-testleri-hypothesis-tests-for-means" class="nav-link" data-scroll-target="#ortalamalar-i%C3%A7in-hipotez-testleri-hypothesis-tests-for-means"><span class="header-section-number">4.2.1</span> Ortalamalar için Hipotez Testleri (Hypothesis Tests for Means)</a></li>
  <li><a href="#iki-%C3%B6rneklem-testleri-two-sample-tests" id="toc-iki-örneklem-testleri-two-sample-tests" class="nav-link" data-scroll-target="#iki-%C3%B6rneklem-testleri-two-sample-tests"><span class="header-section-number">4.2.2</span> İki Örneklem Testleri (two-sample Tests)</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./temel_istatistik.html">Temel İstatistik</a></li><li class="breadcrumb-item"><a href="./hipotez.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Güven Aralıkları ve Hipotez Testleri</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Güven Aralıkları ve Hipotez Testleri</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Güven aralıkları ve hipotez testleri, çıkarımsal istatistikte karar verme süreçlerinin temel araçlarıdır. Güven aralıkları, bir anakütle parametresi için tahmin edilen aralığı sunarak belirsizliği açıkça ifade eder ve tahminin ne kadar güvenilir olduğunu gösterir. Hipotez testleri ise belirli bir iddianın (örneğin, bir ortalamanın veya farkın anlamlılığı) istatistiksel olarak desteklenip desteklenmediğini değerlendirir. Her iki yöntem de, sınırlı örneklem verilerinden anakütle hakkında genelleme yapmaya olanak tanır ve araştırmacıların veriye dayalı, anlamlı ve doğru sonuçlar çıkarmasına yardımcı olur. Bu araçlar olmadan, çıkarımsal analizlerin güvenilirliği ve bilimselliği büyük ölçüde azalır.</p>
<ul>
<li><strong>Örnek veri seti: Çikolata Barları</strong></li>
</ul>
<p>Ankara merkezli bir çikolata üreticisi olan <strong>Ankara Çikolatacısı</strong>, çikolata barlarının ağırlığını (gram cinsinden) ölçmüş ve üretim sürecindeki değişkenliği anlamamızı istemiştir. Bu verileri Normal dağılımdan simüle edeceğiz. Ortalama (<span class="math inline">\(\mu = 40\)</span>) ve satandart sapma (<span class="math inline">\(\sigma = 2\)</span>). Çikolata bar ağırlıklarının gerçek ortalamasını ve varyansını biliyoruz, ancak ilerleyen bölümlerde (örn. t-testi yaparken) bu parametrelerin bilinmediğini varsayabiliriz.</p>
<ul>
<li><strong>Veri Simülasyonu ve İnceleme</strong></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Rastgelelik için sabit bir başlangıç noktası belirleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Normal dağılımdan rastgele veri üretme</span></span>
<span><span class="va">choc.ankara</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span></span>
<span>  <span class="fl">10000</span>,  <span class="co"># Üretilecek rastgele sayıların toplam miktarı</span></span>
<span>  mean <span class="op">=</span> <span class="fl">40</span>,  <span class="co"># Normal dağılımın ortalama değeri</span></span>
<span>  sd <span class="op">=</span> <span class="fl">2</span>  <span class="co"># Normal dağılımın standart sapması</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># İlk birkaç veriyi görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">choc.ankara</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38.74709 40.36729 38.32874 43.19056 40.65902 38.35906</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="hipotez_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="güven-aralığı-confidence-interval---ci" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="güven-aralığı-confidence-interval---ci">
<span class="header-section-number">4.1</span> Güven Aralığı (Confidence Interval - CI)</h2>
<p><a href="https://en.wikipedia.org/wiki/Confidence_interval">Güven aralığı</a>, istatistikte bir anakütle parametresi için bir aralık kestirimi olup, çıkarımsal istatistikte önemli bir araçtır. Tek bir noktadan tahmin yerine, parametrenin belirli bir olasılıkla içinde bulunabileceği alt ve üst sınırlarla tanımlanan bir aralık sunar. Güven aralıkları, tahminin ne kadar güvenilir olduğunu ifade eder ve bu güvenilirlik, seçilen güven düzeyiyle (%90, %95 veya %99 gibi) belirtilir. Yüksek bir güven düzeyi seçildiğinde güven aralığı genişler, bu da parametreyi kapsama olasılığını artırır. Güven aralıkları genellikle, tahmin yönteminin normal dağılım gibi belirli varsayımları karşılaması durumunda hesaplanır. Çıkarımsal istatistikte, anakütle parametreleri hakkında daha anlamlı ve güvenilir sonuçlara ulaşmayı sağlar ve hipotez testleriyle birlikte kullanıldığında analizlerin istatistiksel gücünü artırır.</p>
<p><strong>Güven Aralıklarının Hesaplanması</strong></p>
<p>R’de güven aralıklarını hesaplamak oldukça basittir. Temel R paketinde doğrudan güven aralığı hesaplayan bir fonksiyon bulunmasa da, <code><a href="https://alanarnholt.github.io/BSDA/reference/z.test.html">z.test()</a></code> ve <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> fonksiyonlarını kullanarak ortalamalar için güven aralıklarını hesaplayabiliriz (bu yöntemler oranlar için kullanılamaz).</p>
<section id="popülasyon-standart-sapmasını-biliniyorsa-z.test-fonksiyonu" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="popülasyon-standart-sapmasını-biliniyorsa-z.test-fonksiyonu">
<span class="header-section-number">4.1.1</span> Popülasyon Standart Sapmasını Biliniyorsa: <code>z.test()</code> Fonksiyonu</h3>
<p>Eğer popülasyon standart sapmasını biliyorsak, <code><a href="https://alanarnholt.github.io/BSDA/reference/z.test.html">z.test()</a></code> fonksiyonunu (BSDA paketinden) kullanabiliriz. Bu fonksiyona popülasyon standart sapmasını (<strong>sigma.x</strong>) ve güven düzeyini (<strong>conf.level</strong>) sağlamamız gerekir. Örnek bir kullanım aşağıda verilmiştir:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli paketin yüklenmesi</span></span>
<span><span class="co"># install.packages("BSDA") </span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/alanarnholt/BSDA">"BSDA"</a></span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># z.test fonksiyonu ile güven aralığı hesaplama</span></span>
<span><span class="va">z_test1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://alanarnholt.github.io/BSDA/reference/z.test.html">z.test</a></span><span class="op">(</span></span>
<span>  <span class="va">choc.ankara</span>,       <span class="co"># Analiz edilecek veri seti</span></span>
<span>  sigma.x <span class="op">=</span> <span class="fl">2</span>,       <span class="co"># Popülasyonun bilinen standart sapması</span></span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Güven düzeyi (%95)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Güven aralığını döndürme</span></span>
<span><span class="va">z_test1</span><span class="op">$</span><span class="va">conf.int</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.94773 40.02613
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Hesaplanan güven aralığını döndürür. Bu, belirlenen %95 güven düzeyi ile </span></span>
<span><span class="co"># çikolata barlarının ağırlık ortalaması için tahmin edilen aralıktır.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Bu sonuç, çikolata barlarının ağırlık ortalamasının %95 güven düzeyiyle 39.94773 gram ile 40.02613 gram arasında olduğunu göstermektedir. Başka bir deyişle, elimizdeki verilere dayanarak, gerçek ortalama ağırlığın bu aralıkta yer alması oldukça olasıdır. Ancak, bu güven aralığı %100 kesinlik sunmaz; %5’lik bir hata payı mevcuttur.</p>
<p>Güven düzeyi %95 olarak belirlenmiştir. Bu da, benzer şekilde birçok örneklem üzerinden analiz yapılsa, bu örneklemlerin %95’inin gerçek ortalamayı belirtilen aralıkta içerme olasılığını ifade eder. Dolayısıyla, çikolata barlarının üretim sürecinin genel olarak tutarlı ve standartlara uygun olduğunu söyleyebiliriz. Üretimdeki varyasyonun düşük olması, kalite kontrol süreçlerinin etkili bir şekilde işlediğini göstermektedir.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Neden &quot;%95&quot; Güven Aralığı">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Neden “%95” Güven Aralığı
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Güven aralıkları</strong>nı hesaplarken %95 güven düzeyinin önemi, istatistikte bir denge noktası olarak kabul edilmesinden kaynaklanır. %95 güven düzeyi, bir tahminin güvenilirliğini makul bir kesinlik düzeyinde ifade ederken, aynı zamanda hata payını (%5) da kontrol edilebilir seviyede tutar. Bunun birkaç temel nedeni vardır:</p>
<ol type="1">
<li>
<strong>Pratik Denge:</strong> %95 güven düzeyi, güvenilirlik ve belirsizlik arasında dengeli bir nokta sağlar. Daha yüksek bir güven düzeyi (%99) aralığı genişletir, bu da sonuçları daha az hassas hale getirebilir. Daha düşük bir güven düzeyi (%90) ise daha dar aralık sağlar ancak güvenilirlik azalır. %95, bu ikisi arasında ideal bir denge olarak kabul edilir.</li>
<li>
<strong>Geleneksel Kabul:</strong> İstatistiksel analizde %95 güven düzeyi, literatürde ve uygulamada yaygın olarak kabul edilmiş bir standarttır. Bu standartlaşma, farklı çalışmalar arasında karşılaştırma yapmayı kolaylaştırır.</li>
<li>
<strong>Hata Payı (%5):</strong> %95 güven düzeyi, tahmin edilen aralığın gerçek parametreyi kapsama olasılığının %95 olduğunu, yani yalnızca %5 hata payı olduğunu ifade eder. Bu hata payı, birçok durumda bilimsel kabul için yeterince düşük bulunur.</li>
<li>
<strong>Normatif Kullanım:</strong> Pek çok disiplin ve uygulamada (örneğin, biyoloji, sosyal bilimler, ekonomi) %95 güven düzeyi yaygın olarak kullanılır ve bu düzeyin ötesinde bir anlam çıkarma genellikle “istatistiksel olarak anlamlı” kabul edilir.</li>
<li>
<strong>Z Değeri:</strong> %95 güven düzeyi, standart normal dağılımda <span class="math inline">\(z = \pm 1.96\)</span> sınırına karşılık gelir. Bu, istatistiksel analizlerde kolaylıkla hesaplanabilen ve yorumlanabilen bir değerdir.</li>
</ol>
<p>Sonuç olarak, %95 güven aralığı, tek bir tahminin doğruluğunu ifade etmez. Bunun yerine, birçok örneklem alınarak yapılan hesaplamalarda, bu aralıkların çoğunluğunun (%95) gerçek değeri kapsayacağını garanti eder.</p>
</div>
</div>
</section><section id="popülasyon-standart-sapmasını-bilinmiyorsa-t.test-fonksiyonu" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="popülasyon-standart-sapmasını-bilinmiyorsa-t.test-fonksiyonu">
<span class="header-section-number">4.1.2</span> Popülasyon Standart Sapmasını Bilinmiyorsa: <code>t.test()</code> Fonksiyonu</h3>
<p>Pratikte çoğu zaman popülasyon standart sapmasını bilmediğimiz durumlarla karşılaşırız. Bu durumda <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> fonksiyonunu kullanabiliriz. Burada yalnızca güven düzeyini (<strong>conf.level</strong>) belirteriz ve fonksiyon, standart hatayı kullanarak güven aralığını oluşturur.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># T-testi ile güven aralığı hesaplama</span></span>
<span><span class="va">t_test1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">choc.ankara</span>,       <span class="co"># Analiz edilecek veri seti</span></span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Güven düzeyi (%95)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Hesaplanan güven aralığını döndürme</span></span>
<span><span class="va">t_test1</span><span class="op">$</span><span class="va">conf.int</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.94724 40.02661
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
</section></section><section id="hipotez-testleri-hypothesis-tests" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="hipotez-testleri-hypothesis-tests">
<span class="header-section-number">4.2</span> Hipotez Testleri (Hypothesis Tests)</h2>
<p><a href="https://en.wikipedia.org/wiki/Statistical_hypothesis_test">Hipotez testleri</a>, istatistiksel analizlerde belirli bir iddianın doğruluğunu değerlendirmek için kullanılan yöntemlerdir. Hipotez testi, bir null hipoteze (yokluk hipotezi) karşı kanıtların gücünü değerlendirmek için kullanılan bir istatistiksel yöntemdir. Null hipotez, popülasyonda herhangi bir fark, ilişki veya etkinin olmadığını varsayar. Bu yöntem, null hipotezin doğru olduğunu kabul ederek, örneklem verilerinde gözlemlenen veya daha uç sonuçların olasılığını hesaplar. Bu olasılık, <a href="https://en.wikipedia.org/wiki/P-value">p-değeri</a> ile ifade edilir.</p>
<p>Eğer <a href="https://en.wikipedia.org/wiki/P-value">p-değeri</a> yeterince küçükse (örneğin, genellikle <span class="math inline">\(p&lt;0.05\)</span>), null hipotez reddedilir ve alternatif hipotezin doğru olabileceği sonucuna varılır. Ancak, null hipotez asla “<strong>kabul edilmez</strong>” veya “<strong>kanıtlanmaz</strong>.” Sadece mevcut verilerle <strong>reddedilemeyecek kadar güçlü</strong> olduğu düşünülür.</p>
<p>Bu süreç, bir ceza davasına benzetilebilir: Sanık suçsuz kabul edilir (null hipotez reddedilmez) ancak suçluluğu yeterince güçlü kanıtlarla gösterildiğinde (istatistiksel olarak anlamlı sonuçlar) sanık suçlu ilan edilir (null hipotez reddedilir).</p>
<p>Bu yöntemlerde iki ana hipotez tanımlanır:</p>
<ul>
<li>
<strong>Null hipotez</strong> (<span class="math inline">\(H_0\)</span>): Varsayılan durum ya da iddia (örneğin, iki grup arasında fark yoktur).</li>
<li>
<strong>Alternatif hipotez</strong> (<span class="math inline">\(H_1\)</span>): Test edilmek istenen yeni iddia (örneğin, iki grup arasında fark vardır).</li>
</ul>
<p>Veriler toplandıktan sonra, bu hipotezler istatistiksel araçlarla değerlendirilir. Hipotez testinin sonucunda elde edilen <a href="https://en.wikipedia.org/wiki/P-value">p-değeri</a>, <span class="math inline">\(H_0\)</span>’ın doğru olduğu varsayımı altında gözlemlenen sonuçların olasılığını ifade eder. Eğer p-değeri, önceden belirlenmiş anlamlılık düzeyinden (örneğin, <span class="math inline">\(\alpha\)</span> = 0.05) küçükse, null hipotez reddedilir ve alternatif hipotezin doğru olabileceği kabul edilir.</p>
<p><strong>Adım 1. Araştırma Sorusu Belirlenir</strong></p>
<p>Bir palet çikolata barımız olduğunu ve bunların <strong>Ankara Çikolatacısı</strong>’na ait olup olmadığından emin olmadığımızı varsayalım. Bu çikolata barlarının ağırlıkları, bu barların Ankara Çikolatacısı’na ait olma olasılığı hakkında bize ne söyleyebilir?</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Rastgelelik için sabit bir başlangıç noktası belirleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Normal dağılımdan rastgele veri üretme</span></span>
<span><span class="va">choc.palet</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span></span>
<span>  <span class="fl">20</span>,       <span class="co"># Üretilecek rastgele sayıların toplam miktarı</span></span>
<span>  mean <span class="op">=</span> <span class="fl">42</span>, <span class="co"># Normal dağılımın ortalama değeri</span></span>
<span>  sd <span class="op">=</span> <span class="fl">2</span>     <span class="co"># Normal dağılımın standart sapması</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Veri özet istatistiklerini görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">choc.palet</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  36.22   40.81   41.41   41.62   42.87   45.57 </code></pre>
</div>
</div>
<p><strong>Araştırma sorusu:</strong> “Bu çikolata barlarının ağırlıkları, onların Ankara Çikolatacısı’na ait olduğunu gösteriyor mu?”</p>
<p><strong>Adım 2. Null Hipotezi (</strong><span class="math inline">\(H_0\)</span><strong>), ve Alternatif Hipotez (</strong><span class="math inline">\(H_1\)</span><strong>) Belirlenir</strong></p>
<p>Araştırma sorusuna dayanarak, null ve alternatif hipotezler oluşturulur. Örneğin, Adım 1’deki araştırma sorusunu cevaplamak için, iki grup arasında bir karşılaştırma yapmamız gerekir: Ankara Çikolataları’ndan olduğu varsayılan çikolata barlarının ağırlıkları ve diğer çikolata barlarının ağırlıkları. Bu durumda, her iki grubun popülasyon ortalamalarını sırasıyla <span class="math inline">\(\mu_1\)</span> ve <span class="math inline">\(\mu_2\)</span> olarak ifade edilir.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Yunan Alfabesi ve istatistik Sembolleri">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Yunan Alfabesi ve istatistik Sembolleri
</div>
</div>
<div class="callout-body-container callout-body">
<p>Yunan alfabesindeki <span class="math inline">\(\mu\)</span> (<em>mu</em>) harfi istatistikte popülasyon ortalamasını bembolize etmektedir. Buna benzer olarak, <span class="math inline">\(\sigma\)</span> (sigma), <span class="math inline">\(\alpha\)</span> (<em>alfa</em>) gibi semboller de kullanılmaktadır. Sembollerle alakalı daha fazla bilgi edinmek için: <a href="https://mathvault.ca/hub/higher-math/math-symbols/probability-statistics-symbols/" class="uri">https://mathvault.ca/hub/higher-math/math-symbols/probability-statistics-symbols/</a></p>
</div>
</div>
<p><strong>Null hipotez</strong> <span class="math inline">\(H_0\)</span>, genellikle “<strong>etki yok</strong>” ya da “<strong>fark yok</strong>” ifadesini içeren bir parametre durumu olmalıdır. Bu örnekte, null hipotez şu şekilde ifade edilir:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> ya da <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span></p>
<blockquote class="blockquote">
<p>Bu, çikolata barlarının ağırlıklarının Ankara Çikolataları’nın ortalama ağırlığı olan (<span class="math inline">\(\mu_1 = 40\)</span>) 40 gramdan <strong>farklı olmadığını</strong> varsayar.</p>
</blockquote>
<p><strong>Alternatif hipotez</strong> (<span class="math inline">\(H_1\)</span>), genellikle doğru olduğunu düşündüğümüz ya da test etmek istediğimiz iddiayı ifade eder. Bu durumda, alternatif hipotez şu şekilde olabilir:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1 \neq \mu_2\)</span> ya da <span class="math inline">\(\mu_1 - \mu_2 \neq 0\)</span></p>
<blockquote class="blockquote">
<p>Bu, çikolata barlarının ağırlıklarının Ankara Çikolataları’nın ortalama ağırlığından (<span class="math inline">\(\mu_1 = 40\)</span>) <strong>farklı</strong> olduğunu ifade eder.</p>
</blockquote>
<p><strong>Adım 3. Test İstatistiği ve p-değeri Hesaplanır</strong></p>
<section id="ortalamalar-için-hipotez-testleri-hypothesis-tests-for-means" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="ortalamalar-için-hipotez-testleri-hypothesis-tests-for-means">
<span class="header-section-number">4.2.1</span> Ortalamalar için Hipotez Testleri (Hypothesis Tests for Means)</h3>
<section id="standart-sapma-biliniyorsa-known-standard-deviation" class="level4" data-number="4.2.1.1"><h4 data-number="4.2.1.1" class="anchored" data-anchor-id="standart-sapma-biliniyorsa-known-standard-deviation">
<span class="header-section-number">4.2.1.1</span> Standart Sapma Biliniyorsa (Known Standard Deviation)</h4>
<p>Bir palet çikolata üzerinde, bu çikolataların Ankara Çikolataları’na ait olup olmadığını test etmek isteniyor. Bu amaçla, popülasyon standart sapmasının bilindiği durumda kullanılan <strong>z-testi</strong> yöntemi kullanılır. Test sırasında şu hipotezler tanımlanır:</p>
<ul>
<li><p><strong>Null hipotez (</strong><span class="math inline">\(H_0\)</span><strong>):</strong> Çikolata paletinde yer alan çikolataların ağırlık ortalaması Ankara Çikolataları’nın ortalaması olan 40 gramdır (<span class="math inline">\(\mu_1 = \mu_2 = 40\)</span>).</p></li>
<li><p><strong>Alternatif hipotez</strong> (<span class="math inline">\(H_1\)</span>): Çikolata paletinde yer alan çikolataların ağırlık ortalaması 40 gramdan farklıdır (<span class="math inline">\(\mu_1 \neq \mu_2 \neq 40\)</span>).</p></li>
</ul>
<p>Popülasyon standart sapmasının <span class="math inline">\(\sigma = 2\)</span> olduğu bilindiğinden (<em>adım 1.’de <code>choc.palet</code> veri setinde standart sapma 2 (<code>sd = 2</code>) olarak belirlenmişti.</em>), bu değer <strong>z-testi</strong> sırasında kullanılacaktır. Ayrıca, güven düzeyini <span class="math inline">\(1 - \alpha = 0.95\)</span> (yani %95) olarak belirledik. Testi gerçekleştirmek için <strong>BSDA</strong> paketindeki <code><a href="https://alanarnholt.github.io/BSDA/reference/z.test.html">z.test()</a></code> fonksiyonunu kullanılır. Test sonucunda elde edilen <strong>p-değeri</strong>, null hipotezin doğru olduğu varsayımı altında gözlemlenen verilerin veya daha uç sonuçların olasılığını gösterecektir.</p>
<p>Eğer hesaplanan p-değeri, belirlenen anlamlılık düzeyinden (<span class="math inline">\(1 - \alpha = 0.95\)</span>, yani yüzde 95 güven aralığı) küçükse, null hipotezi reddedilir. Bu durumda, çikolataların Ankara Çikolataları’na ait olmadığı sonucuna varabilir. Eğer p-değeri büyükse, null hipotezi reddedemeyiz ve çikolataların ağırlıklarının Ankara Çikolataları’na ait olduğu varsayımını destekleyen bir sonuç elde edilmiş olur.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanenin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/alanarnholt/BSDA">BSDA</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Z-testi ile hipotez testi</span></span>
<span><span class="va">z_test2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://alanarnholt.github.io/BSDA/reference/z.test.html">z.test</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="va">choc.palet</span>,     <span class="co"># Test edilecek veri: Çikolata barlarının ağırlıkları</span></span>
<span>  mu <span class="op">=</span> <span class="fl">40</span>,            <span class="co"># Null hipotezdeki popülasyon ortalaması: 40 gram</span></span>
<span>  sigma.x <span class="op">=</span> <span class="fl">2</span>,        <span class="co"># Popülasyon standart sapması: 2 gram</span></span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span>   <span class="co"># Güven düzeyi: %95</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Hesaplanan p-değerini görüntüleme</span></span>
<span><span class="va">z_test2</span><span class="op">$</span><span class="va">p.value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002807644</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Test sonucunda elde edilen <strong>p-değeri = 0.0002807644</strong>, genellikle kabul edilen anlamlılık düzeyi olan <span class="math inline">\(\alpha = 0.05\)</span>’ten (hatta <span class="math inline">\(\alpha = 0.01\)</span>’den) oldukça küçüktür. Bu, gözlemlenen verilerin null hipotez (<span class="math inline">\(H_0 = \mu_2 = 40\)</span>) doğru olduğu varsayımı altında ortaya çıkma olasılığının son derece düşük olduğunu göstermektedir. Bu nedenle, <strong>null hipotez reddedilmektedir</strong>.</p>
<p>Bu sonuca göre, çikolata paletindeki çikolataların ağırlık ortalamasının Ankara Çikolataları’nın standart ağırlık ortalaması olan 40 gramdan <strong>anlamlı derecede farklı</strong> olduğu söylenebilir. Dolayısıyla, bu çikolataların Anakara Çikolataları’na ait olmadığını gözlemlenen farkın tesadüfen oluşma olasılığının çok düşük olduğunu ifade etmektedir.</p>
<p><strong>Sonuç olarak</strong> bu test sonuçlarına dayanarak, çikolata paletindeki çikolataların Ankara Çikolataları’na ait olmadığı yönünde güçlü bir kanıya varılabilir.</p>
</blockquote>
</section><section id="standart-sapma-bilinmiyorsa-unknown-standard-deviation" class="level4" data-number="4.2.1.2"><h4 data-number="4.2.1.2" class="anchored" data-anchor-id="standart-sapma-bilinmiyorsa-unknown-standard-deviation">
<span class="header-section-number">4.2.1.2</span> Standart Sapma Bilinmiyorsa (Unknown Standard Deviation)</h4>
<p>Bir palet çikolata üzerinde, bu çikolataların Ankara Çikolataları’na ait olup olmadığını test etmek isteniyor. Ancak bu durumda, popülasyon standart sapmasının bilinmediği varsayılmaktadır. Standart sapmanın bilinmediği durumlarda, <strong>t-testi</strong> yöntemi kullanılır ve bu yöntem R’ın temel fonksiyonlarından olan <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> ile kolaylıkla uygulanabilir. Bu yöntem, aşağıdaki formül ile tanımlanan dağılıma dayanır:</p>
<p><span class="math inline">\(\frac{\bar{X} - \mu}{\frac{s_x}{\sqrt{n}}} \sim t_{n-1}\)</span></p>
<p>Burada <span class="math inline">\(t_{n-1}\)</span> , <span class="math inline">\(n-1\)</span> serbestlik derecesine sahip <strong>Student’s t-dağılımı</strong>nı ifade eder. Testi gerçekleştirmek için yalnızca güven düzeyini belirtmek yeterlidir. Örneğin, güven düzeyi <span class="math inline">\(1 - \alpha = 0.95\)</span> olarak belirlenebilir. Bu durumda, çikolata paletindeki çikolataların Ankara Çikolataları’na ait olup olmadığı, popülasyon standart sapması bilinmeden değerlendirilmiş olur.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># T-testi ile hipotez testi</span></span>
<span><span class="va">t_test2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="va">choc.palet</span>,     <span class="co"># Test edilecek veri: Çikolata paleti ağırlıkları</span></span>
<span>  mu <span class="op">=</span> <span class="fl">40</span>,            <span class="co"># Null hipotezdeki popülasyon ortalaması: 40 gram</span></span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span>   <span class="co"># Güven düzeyi: %95</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Hesaplanan p-değerini görüntüleme</span></span>
<span><span class="va">t_test2</span><span class="op">$</span><span class="va">p.value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003109143</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Test sonucunda elde edilen <strong>p-değeri = 0.0031</strong>, genellikle kabul edilen anlamlılık düzeyi olan <span class="math inline">\(\alpha = 0.05\)</span>’ten küçük bir değerdir. Bu durum, null hipotezin (<span class="math inline">\(H_0 = \mu_2 = 40\)</span>) doğru olduğu varsayımı altında, gözlemlenen verilerin veya daha uç sonuçların ortaya çıkma olasılığının oldukça düşük olduğunu göstermektedir. Bu nedenle, <strong>null hipotez reddedilmektedir</strong>.</p>
<p>Bu sonuca göre, çikolata paletindeki çikolataların ağırlık ortalamasının Ankara Çikolataları’nın standart ağırlık ortalaması olan 40 gramdan anlamlı derecede farklı olduğu söylenebilir. Elde edilen düşük p-değeri, bu farkın istatistiksel olarak güçlü bir anlamlılık taşıdığını ve gözlemlenen sonucun rastgele oluşma ihtimalinin oldukça düşük olduğunu ifade etmektedir.</p>
<p><strong>Sonuç olarak</strong>, çikolata paletindeki çikolataların Ankara Çikolataları’na ait olmadığı yönünde güçlü bir bulgu elde edilmiştir. Bu çikolataların başka bir üreticiye ait olabileceği değerlendirilmektedir.</p>
</blockquote>
</section></section><section id="iki-örneklem-testleri-two-sample-tests" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="iki-örneklem-testleri-two-sample-tests">
<span class="header-section-number">4.2.2</span> İki Örneklem Testleri (two-sample Tests)</h3>
<section id="birleştirilmemiş-iki-örneklem-t-testi-unpooled-two-sample-t-test" class="level4" data-number="4.2.2.1"><h4 data-number="4.2.2.1" class="anchored" data-anchor-id="birleştirilmemiş-iki-örneklem-t-testi-unpooled-two-sample-t-test">
<span class="header-section-number">4.2.2.1</span> Birleştirilmemiş İki Örneklem t-testi (Unpooled Two-sample t-test)</h4>
<p>İki farklı çikolata partisini karşılaştırarak, bunların aynı fabrikadan gelip gelmediklerini test etmek istiyoruz. İlk parti 40, ikinci parti 45 paket çikolatadan oluşmaktadır. Popülasyon ortalamaları (<span class="math inline">\(\mu_1\)</span> ve <span class="math inline">\(\mu_2\)</span>) ve standart sapmaları bilinmediğinden, bu partiler arasındaki farkı değerlendirmek için <strong>birleştirilmemiş iki örneklem t-testi</strong> uygulanır.</p>
<p><strong>Hipotezler:</strong></p>
<ul>
<li>Null hipotez (<span class="math inline">\(H_0\)</span>): İki partinin ortalamaları arasında fark yoktur (<span class="math inline">\(\mu_1 = \mu_2 = 40\)</span>).</li>
<li>Alternatif hipotez (<span class="math inline">\(H_1\)</span>): İki partinin ortalamaları arasında fark vardır (<span class="math inline">\(\mu_1 \neq \mu_2 \neq 40\)</span>).</li>
</ul>
<p>Örneklem verilerini, ortalamaları sırasıyla 45 ve 47 olan normal dağılımlardan üreteceğiz. Ancak, bu bilgilerin bilinmediğini varsayacağız. Ayrıca, örneklem aldığımız dağılımların popülasyon standart sapmalarının 2 olduğu bilinse de, test sırasında bu bilginin de mevcut olmadığını kabul edeceğiz. Gerçek popülasyon ortalamalarını <span class="math inline">\(\mu_1\)</span> ve <span class="math inline">\(\mu_2\)</span> ile ifade edeceğiz.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanenin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Tekrarlanabilirlik için rastgelelik sabitleniyor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Verilerin simülasyonu</span></span>
<span><span class="va">parti1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span>, mean <span class="op">=</span> <span class="fl">45</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># Birinci partinin ağırlıkları</span></span>
<span><span class="va">parti2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">45</span>, mean <span class="op">=</span> <span class="fl">47</span>, sd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># İkinci partinin ağırlıkları</span></span>
<span></span>
<span><span class="co"># Veri çerçevesi oluşturma</span></span>
<span><span class="va">Parti</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"1"</span>, <span class="fl">40</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"2"</span>, <span class="fl">45</span><span class="op">)</span><span class="op">)</span> <span class="co"># Partileri temsil eden faktör değişken</span></span>
<span><span class="va">Cikolata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">parti1</span>, <span class="va">parti2</span><span class="op">)</span>          <span class="co"># Birleştirilmiş çikolata ağırlıkları</span></span>
<span><span class="va">tablo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">Parti</span>, <span class="va">Cikolata</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Boxplot ile görselleştirme</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">tablo</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Parti</span>, y <span class="op">=</span> <span class="va">Cikolata</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Cikolata Partilerinin Agirlik Dagilimi"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Parti"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Agirlik"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="hipotez_files/figure-html/cikolata-parti-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Birleştirilmemiş iki örneklem T-testi</span></span>
<span><span class="va">t_test3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">parti1</span>,              <span class="co"># Birinci örneklem verisi</span></span>
<span>  <span class="va">parti2</span>               <span class="co"># İkinci örneklem verisi</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Test sonuçlarını görüntüleme</span></span>
<span><span class="va">t_test3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  parti1 and parti2
t = -4.8753, df = 82.135, p-value = 5.227e-06
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.699807 -1.135072
sample estimates:
mean of x mean of y 
 45.09037  47.00781 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Elde edilen <strong>p-değeri = 5.227e-06</strong>, genellikle kabul edilen anlamlılık düzeyi olan <span class="math inline">\(\alpha = 0.05\)</span>’ten ve hatta <span class="math inline">\(\alpha = 0.01\)</span>’den bile çok küçüktür. Bu durum, iki çikolata partisinin ağırlık ortalamalarının aynı olduğu null hipotezin (<span class="math inline">\(H_0\)</span>) doğru olma olasılığının son derece düşük olduğunu göstermektedir. Bu nedenle, <strong>null hipotez reddedilmektedi</strong>r.</p>
<p>Bu sonuca göre, iki çikolata partisi arasında ağırlık ortalamaları açısından anlamlı bir fark olduğu ve partilerin muhtemelen farklı fabrikalardan geldiği söylenebilir.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="e-&quot; nedir?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
e-” nedir?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“e-”</strong> ifadesi, bilimsel gösterimde kullanılan bir kısaltmadır ve “10 üzeri” anlamına gelir. Örneğin, <strong>5.227e-06</strong> ifadesi, <span class="math inline">\(5.227 \times 10^{-6}\)</span> yani <strong>0.000005227</strong> anlamına gelir. Bu gösterim, çok küçük veya çok büyük sayıları kolayca ifade etmek için kullanılır.</p>
</div>
</div>
<p>Bu sefer de <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> yerine <span class="math inline">\(H_1:\mu_1 \leq \mu_2\)</span> hipotezi test edilsin.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Tek yönlü T-testi</span></span>
<span><span class="va">t_test4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">parti1</span>,                <span class="co"># Birinci örneklem verisi</span></span>
<span>  <span class="va">parti2</span>,                <span class="co"># İkinci örneklem verisi</span></span>
<span>  alternative <span class="op">=</span> <span class="st">"less"</span><span class="op">)</span></span>
<span><span class="co"># Tek yönlü test: Birinci partinin ortalamasının, ikinci partinin ortalamasına </span></span>
<span><span class="co"># eşit veya daha küçük olduğunu test eder</span></span>
<span></span>
<span><span class="co"># Test sonuçlarını görüntüleme</span></span>
<span><span class="va">t_test4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  parti1 and parti2
t = -4.8753, df = 82.135, p-value = 2.614e-06
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
      -Inf -1.263149
sample estimates:
mean of x mean of y 
 45.09037  47.00781 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>P-değeri = 2.614e-06</strong> olduğu için <strong>null hipotez reddedilir</strong>. Birinci partinin ağırlık ortalamasının, ikinci partininkinden anlamlı derecede daha küçük olduğu sonucuna varılır (<span class="math inline">\(\mu_1 \leq \mu_2\)</span>).</p>
</blockquote>
<p>Bu testte, tek yönlü bir hipotez testi uygulandığı için null hipotezin reddedildiği sonucuna varılmıştır. Tek yönlü testler, pratikte daha yaygındır çünkü veri setleri arasındaki ilişkinin daha odaklı bir açıklamasını sağlar. Örneğin, devlet yardımı alan firmaların ihracat performanslarını değerlendirdiğimizi düşünelim. Burada, yardımların ihracatı artırıp artırmadığıyla ilgileniyoruz, yani tek yönlü bir alternatif hipotez (<span class="math inline">\(H_1 :ihracat performansı artar\)</span>) kullanırız. Yardımların sadece ihracatı değiştirdiğini, ancak artıp artmadığını bilmediğimiz bir durumda ise iki yönlü bir alternatif hipotez (<span class="math inline">\(H_1:ihracat performansı farklıdır\)</span>} tercih edilir. Ancak genelde bu tür analizlerde asıl odak, ihracatın artması üzerindedir, bu yüzden tek yönlü test daha uygun olur.</p>
</section><section id="birleştirilmiş-iki-örneklem-t-testi-pooled-two-sample-t-test" class="level4" data-number="4.2.2.2"><h4 data-number="4.2.2.2" class="anchored">
<span class="header-section-number">4.2.2.2</span> Birleştirilmiş İki Örneklem t-testi (Pooled Two-sample t-test)</h4>
<p>Eğer örneklemlerin aynı standart sapmaya sahip dağılımlardan geldiğini biliyorsanız, birleştirilmiş iki örneklem t-testi (pooled t-test) uygulanabilir. Bu test, iki grup arasında ortalamalar açısından fark olup olmadığını değerlendirmek için kullanılır ve grup varyanslarının eşit olduğu varsayılır. R’de bu test, t.test fonksiyonunda var.equal = TRUE argümanı ile belirtilir.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Birleştirilmiş iki örneklem T-testi</span></span>
<span><span class="va">t_test_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">parti1</span>,           <span class="co"># Birinci parti verisi</span></span>
<span>  <span class="va">parti2</span>,           <span class="co"># İkinci parti verisi</span></span>
<span>  var.equal <span class="op">=</span> <span class="cn">TRUE</span>  <span class="co"># Varyansların eşit olduğu varsayımı</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Test sonuçlarını görüntüleme</span></span>
<span><span class="va">t_test_pooled</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  parti1 and parti2
t = -4.8705, df = 83, p-value = 5.254e-06
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.700462 -1.134417
sample estimates:
mean of x mean of y 
 45.09037  47.00781 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<ol type="1">
<li>
<p><strong>t-istatistiği</strong> (<span class="math inline">\(t=−4.8705\)</span>):</p>
<ul>
<li>T-testi sonucunda hesaplanan t-değeri, iki grup arasındaki ortalama farkın standart hata cinsinden ne kadar uzakta olduğunu gösterir. Burada elde edilen negatif değer, birinci grubun ortalamasının ikinci grubunkinden daha düşük olduğunu işaret eder.</li>
</ul>
</li>
<li>
<p><strong>Serbestlik Derecesi</strong> (<span class="math inline">\(df=83\)</span>):</p>
<ul>
<li>Testte kullanılan serbestlik derecesi, veri setlerinin boyutlarına ve test türüne bağlıdır. Burada, iki grubun toplam gözlem sayısından (40 + 45) varyans hesaplamaları için kullanılan parametreler çıkarılarak <span class="math inline">\(df=83\)</span> elde edilmiştir.</li>
</ul>
</li>
<li>
<p><strong>P-değeri</strong> :</p>
<ul>
<li><p>Elde edilen <strong>p-değeri = 5.254e-06</strong>, kabul edilen anlamlılık düzeyi (<span class="math inline">\(\alpha=0.05\)</span>) ve hatta daha düşük bir düzey olan (<span class="math inline">\(\alpha=0.05\)</span>) ile karşılaştırıldığında oldukça küçüktür. Bu, null hipotezin (<span class="math inline">\(H_0\)</span>: iki grup ortalaması arasında fark yoktur) reddedilmesine neden olur.</p></li>
<li><p>Sonuç: İki grup arasında ortalamalar açısından <strong>istatistiksel olarak anlamlı bir fark</strong> vardır.</p></li>
</ul>
</li>
<li>
<p><strong>Güven Aralığı</strong>:</p>
<ul>
<li><p>%95 güven düzeyi ile, iki grup arasındaki ortalama farkın popülasyonda −2.7-2.7−2.7 ile −1.13-1.13−1.13 arasında olduğu tahmin edilmektedir.</p></li>
<li><p>Negatif aralık, birinci grubun ortalamasının ikinci grubunkinden daha düşük olduğunu teyit eder.</p></li>
</ul>
</li>
<li>
<p><strong>Örneklem Ortalamaları</strong></p>
<ul>
<li>Birinci grup (x): Ortalama ağırlık <strong>45.09</strong>.</li>
<li>İkinci grup (y): Ortalama ağırlık <strong>47.01</strong>.</li>
<li>Bu fark, test sonuçlarında da anlamlı bulunmuştur.</li>
</ul>
</li>
</ol>
<h3 id="sonuç" data-number="4.2.3" class="anchored" data-anchor-id="birleştirilmiş-iki-örneklem-t-testi-pooled-two-sample-t-test">
<span class="header-section-number">4.2.3</span> <strong>Sonuç:</strong>
</h3>
<p>Bu test, iki çikolata partisi arasındaki ağırlık ortalamalarının anlamlı derecede farklı olduğunu göstermektedir. Elde edilen negatif değerler, birinci partinin ortalamasının ikinci partininkinden daha düşük olduğunu desteklemektedir. İstatistiksel olarak anlamlı bu fark, partilerin muhtemelen farklı fabrikalardan geldiğini düşündürmektedir.</p>
</blockquote>
<p><strong>Referans</strong></p>
<p><a href="https://rpubs.com/syedafzalali/R3" class="uri">https://rpubs.com/syedafzalali/R3</a></p>
<p><a href="https://uw-statistics.github.io/Stat311Tutorial/confidence-intervals.html" class="uri">https://uw-statistics.github.io/Stat311Tutorial/confidence-intervals.html</a></p>
<p><a href="https://uw-statistics.github.io/Stat311Tutorial/hypothesis-tests.html" class="uri">https://uw-statistics.github.io/Stat311Tutorial/hypothesis-tests.html</a></p>
<p><a href="https://www.modernstatisticswithr.com/basicstatistics.html" class="uri">https://www.modernstatisticswithr.com/basicstatistics.html</a></p>
<p><a href="https://openintro-ims.netlify.app/foundations-of-inference" class="uri">https://openintro-ims.netlify.app/foundations-of-inference</a></p>
<p><a href="https://bookdown.org/pbaumgartner/swr-harris/" class="uri">https://bookdown.org/pbaumgartner/swr-harris/</a></p>
<div style="page-break-after: always;"></div>


</section></section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./dagilim.html" class="pagination-link" aria-label="Dağılım Türleri ve Merkezi Limit Teoremi">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Dağılım Türleri ve Merkezi Limit Teoremi</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./veri_donusum.html" class="pagination-link" aria-label="Veri Dönüşümleri">
        <span class="nav-page-text">Veri Dönüşümleri</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>