<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>6&nbsp; Veri Temizleme – R ile İstatistiğe Giriş ve Veri Dönüşümü</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./veri_manipulasyonu.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./veri_donusum.html">Veri Dönüşümleri</a></li><li class="breadcrumb-item"><a href="./veri_temizleme.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Veri Temizleme</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R ile İstatistiğe Giriş ve Veri Dönüşümü</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/cetinservet/veritemizleme" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-ile-İstatistiğe-Giriş-ve-Veri-Dönüşümü.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-ile-İstatistiğe-Giriş-ve-Veri-Dönüşümü.docx">
              <i class="bi bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
</div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Önsöz</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Giriş</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./temel_istatistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Temel İstatistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_tipleri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">İstatistikte Veri Tipleri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ozet_istatistikler.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Merkezi Eğilim ve Yayılım Ölçüleri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dagilim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Dağılım Türleri ve Merkezi Limit Teoremi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hipotez.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Güven Aralıkları ve Hipotez Testleri</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./veri_donusum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Veri Dönüşümleri</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_manipulasyonu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Veri Manipülasyonu</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./veri_temizleme.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Veri Temizleme</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referanslar</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">İçindekiler</h2>
   
  <ul>
<li>
<a href="#eksik-verilerle-%C3%A7al%C4%B1%C5%9Fma" id="toc-eksik-verilerle-çalışma" class="nav-link active" data-scroll-target="#eksik-verilerle-%C3%A7al%C4%B1%C5%9Fma"><span class="header-section-number">6.1</span> Eksik Verilerle Çalışma</a>
  <ul class="collapse">
<li><a href="#ad-hoc-y%C3%B6ntemler---liste-bazl%C4%B1-silme-listwise-deletion" id="toc-ad-hoc-yöntemler---liste-bazlı-silme-listwise-deletion" class="nav-link" data-scroll-target="#ad-hoc-y%C3%B6ntemler---liste-bazl%C4%B1-silme-listwise-deletion"><span class="header-section-number">6.1.1</span> Ad-hoc Yöntemler - Liste Bazlı Silme (Listwise Deletion)</a></li>
  <li><a href="#eksik-verilerin-grafik-olarak-tespiti" id="toc-eksik-verilerin-grafik-olarak-tespiti" class="nav-link" data-scroll-target="#eksik-verilerin-grafik-olarak-tespiti"><span class="header-section-number">6.1.2</span> Eksik Verilerin Grafik Olarak Tespiti</a></li>
  <li><a href="#eksik-de%C4%9Ferlerin-toplam-say%C4%B1lar%C4%B1-ve-oranlar%C4%B1" id="toc-eksik-değerlerin-toplam-sayıları-ve-oranları" class="nav-link" data-scroll-target="#eksik-de%C4%9Ferlerin-toplam-say%C4%B1lar%C4%B1-ve-oranlar%C4%B1"><span class="header-section-number">6.1.3</span> Eksik Değerlerin Toplam Sayıları ve Oranları</a></li>
  <li><a href="#web-raporu-olu%C5%9Fturma" id="toc-web-raporu-oluşturma" class="nav-link" data-scroll-target="#web-raporu-olu%C5%9Fturma"><span class="header-section-number">6.1.4</span> Web Raporu Oluşturma</a></li>
  <li><a href="#dlookr-paketi-ile-eksik-de%C4%9Ferleri-doldurma" id="toc-dlookr-paketi-ile-eksik-değerleri-doldurma" class="nav-link" data-scroll-target="#dlookr-paketi-ile-eksik-de%C4%9Ferleri-doldurma"><span class="header-section-number">6.1.5</span> <code>DLOOKR</code> Paketi ile Eksik Değerleri Doldurma</a></li>
  <li><a href="#mice-paketi-ile-eksik-de%C4%9Ferleri-doldurma" id="toc-mice-paketi-ile-eksik-değerleri-doldurma" class="nav-link" data-scroll-target="#mice-paketi-ile-eksik-de%C4%9Ferleri-doldurma"><span class="header-section-number">6.1.6</span> <code>MICE</code> Paketi ile Eksik Değerleri Doldurma</a></li>
  </ul>
</li>
  <li>
<a href="#ayk%C4%B1r%C4%B1-de%C4%9Ferler-ile-%C3%A7al%C4%B1%C5%9Fma" id="toc-aykırı-değerler-ile-çalışma" class="nav-link" data-scroll-target="#ayk%C4%B1r%C4%B1-de%C4%9Ferler-ile-%C3%A7al%C4%B1%C5%9Fma"><span class="header-section-number">6.2</span> Aykırı Değerler ile Çalışma</a>
  <ul class="collapse">
<li><a href="#ayk%C4%B1r%C4%B1-de%C4%9Ferlerin-tespiti" id="toc-aykırı-değerlerin-tespiti" class="nav-link" data-scroll-target="#ayk%C4%B1r%C4%B1-de%C4%9Ferlerin-tespiti"><span class="header-section-number">6.2.1</span> Aykırı Değerlerin Tespiti</a></li>
  <li><a href="#ayk%C4%B1r%C4%B1-de%C4%9Ferlerin-%C3%A7%C4%B1kar%C4%B1lmas%C4%B1-veya-d%C3%BCzenlenmesi" id="toc-aykırı-değerlerin-çıkarılması-veya-düzenlenmesi" class="nav-link" data-scroll-target="#ayk%C4%B1r%C4%B1-de%C4%9Ferlerin-%C3%A7%C4%B1kar%C4%B1lmas%C4%B1-veya-d%C3%BCzenlenmesi"><span class="header-section-number">6.2.2</span> Aykırı Değerlerin Çıkarılması veya Düzenlenmesi</a></li>
  </ul>
</li>
  <li>
<a href="#veri-d%C3%B6n%C3%BC%C5%9F%C3%BCmleri-ve-standardizasyon" id="toc-veri-dönüşümleri-ve-standardizasyon" class="nav-link" data-scroll-target="#veri-d%C3%B6n%C3%BC%C5%9F%C3%BCmleri-ve-standardizasyon"><span class="header-section-number">6.3</span> Veri Dönüşümleri ve Standardizasyon</a>
  <ul class="collapse">
<li><a href="#matematiksel-d%C3%B6n%C3%BC%C5%9F%C3%BCmler" id="toc-matematiksel-dönüşümler" class="nav-link" data-scroll-target="#matematiksel-d%C3%B6n%C3%BC%C5%9F%C3%BCmler"><span class="header-section-number">6.3.1</span> Matematiksel Dönüşümler</a></li>
  <li><a href="#standardizasyon-ve-normalizasyon" id="toc-standardizasyon-ve-normalizasyon" class="nav-link" data-scroll-target="#standardizasyon-ve-normalizasyon"><span class="header-section-number">6.3.2</span> Standardizasyon ve Normalizasyon</a></li>
  </ul>
</li>
  <li>
<a href="#veri-do%C4%9Frulama-ve-temizleme-i%C5%9Flemleri" id="toc-veri-doğrulama-ve-temizleme-işlemleri" class="nav-link" data-scroll-target="#veri-do%C4%9Frulama-ve-temizleme-i%C5%9Flemleri"><span class="header-section-number">6.4</span> Veri Doğrulama ve Temizleme İşlemleri</a>
  <ul class="collapse">
<li><a href="#veri-t%C3%BCrlerinin-d%C3%BCzenlenmesi" id="toc-veri-türlerinin-düzenlenmesi" class="nav-link" data-scroll-target="#veri-t%C3%BCrlerinin-d%C3%BCzenlenmesi"><span class="header-section-number">6.4.1</span> Veri Türlerinin Düzenlenmesi</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./veri_donusum.html">Veri Dönüşümleri</a></li><li class="breadcrumb-item"><a href="./veri_temizleme.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Veri Temizleme</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Veri Temizleme</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="eksik-verilerle-çalışma" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="eksik-verilerle-çalışma">
<span class="header-section-number">6.1</span> Eksik Verilerle Çalışma</h2>
<p>Büyük veri, hacim, hız, çeşitlilik, doğruluk ve değer gibi özellikleriyle öne çıkar. Bu karmaşık veri dünyasında anlamlı bilgiler çıkarma ve analiz süreçlerini yönetme görevi veri bilimine düşmektedir. Ancak, büyük veri analizi sürecinde en sık karşılaşılan zorluklardan biri eksik verilerdir. Eksik veriler, genellikle yanıt eksiklikleri veya veri kaybı gibi nedenlerle ortaya çıkar ve bu durum, analiz sonuçlarının doğruluğunu ve güvenilirliğini tehlikeye atar. Eksik veri problemi, istatistiksel gücün azalması, parametre tahminlerinde yanlılık, örneklemlerin temsil gücünün zayıflaması ve analiz süreçlerinin karmaşıklaşması gibi sorunlara yol açabilir. Bu nedenle, eksik verilerle doğru bir şekilde başa çıkmak, sağlam ve güvenilir analiz sonuçları elde etmek için kritik öneme sahiptir.</p>
<p><a href="https://www.rpubs.com/justjooz/miss_data" class="uri">https://www.rpubs.com/justjooz/miss_data</a></p>
<p>Eksik veri yönetimi, veri analizi sürecinin temel yapı taşlarından biri olarak değerlendirilmelidir. Bu bağlamda, eksik verilerin tespiti ve görselleştirilmesi için <strong>naniar</strong> paketi kullanılabilir; özellikle <code><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss()</a></code> fonksiyonu, eksik veri desenlerini analiz etmek için etkili bir araçtır. Eksik verileri doldurma yöntemleri arasında, özellikle çok değişkenli veri setleri için uygun olan <strong>mice</strong> paketi dikkat çeker. Bu paket, birden fazla doldurma yöntemi sunarak, veri setinin istatistiksel gücünü ve temsiliyetini artırır. Ayrıca, eksik veri profillerini detaylı bir şekilde analiz etmek ve raporlamak için <strong>dlookr</strong> paketi gibi araçlardan yararlanmak mümkündür. Eksik veri yönetiminde kullanılan bu yaklaşımlar, veri analistlerinin daha doğru öngörüler yapmasını sağlayarak, stratejik karar alma süreçlerine destek olur. Böylece, eksik veri probleminin üstesinden gelmek için yöntem seçimi ve uygulaması, veri analizinde güvenilirlik ve doğruluk açısından vazgeçilmez bir süreçtir.</p>
<p><strong>Veri Seti <code>airquality</code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanelerin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="co"># datasets paketini yükleme (otomatik olarak yüklü olmalı)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">datasets</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># airquality veri setinin görüntülenmesi</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Ozone Solar.R Wind Temp Month Day
1     41     190  7.4   67     5   1
2     36     118  8.0   72     5   2
3     12     149 12.6   74     5   3
4     18     313 11.5   62     5   4
5     NA      NA 14.3   56     5   5
6     28      NA 14.9   66     5   6
7     23     299  8.6   65     5   7
8     19      99 13.8   59     5   8
9      8      19 20.1   61     5   9
10    NA     194  8.6   69     5  10</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Airquality Veri Seti</strong></p>
<p><strong><code>airquality</code></strong> veri seti, 1973 yılında New York’ta ölçülen hava kalitesi değerlerini içeren bir veri setidir. Bu veri seti, hava kalitesini etkileyen çeşitli değişkenleri içerir ve çevresel analizler için kullanılır. Veri seti, aşağıdaki değişkenlerden oluşur:</p>
<ul>
<li>
<strong>Ozone</strong>: Ozon seviyelerini ifade eder (ppb - parts per billion).</li>
<li>
<strong>Solar.R</strong>: Solar radyasyon değerlerini içerir (langley).</li>
<li>
<strong>Wind</strong>: Rüzgar hızını içerir (mph - miles per hour).</li>
<li>
<strong>Temp</strong>: Günlük maksimum sıcaklık ölçümlerini içerir (Fahrenheit).</li>
<li>
<strong>Month</strong>: Ölçümün yapıldığı ayı temsil eder (1-12 arasında).</li>
<li>
<strong>Day</strong>: Ölçümün yapıldığı gün bilgisini içerir (1-31 arasında).</li>
</ul>
</blockquote>
<section id="ad-hoc-yöntemler---liste-bazlı-silme-listwise-deletion" class="level3" data-number="6.1.1"><h3 data-number="6.1.1" class="anchored" data-anchor-id="ad-hoc-yöntemler---liste-bazlı-silme-listwise-deletion">
<span class="header-section-number">6.1.1</span> Ad-hoc Yöntemler - Liste Bazlı Silme (Listwise Deletion)</h3>
<p>Eksik verilerle başa çıkmak için veri bilimciler tarafından en sık kullanılan yöntemlerden biri, eksik değerlere sahip durumları tamamen çıkarmak ve yalnızca kalan veri setini analiz etmektir. Bu yönteme <strong>liste bazlı silme</strong> veya <strong>tam durum analizi</strong> (complete-case analysis) denir. R programında <code><a href="https://rdrr.io/r/stats/na.fail.html">na.omit()</a></code> fonksiyonu, veri setinde bir veya daha fazla eksik değeri olan tüm durumları kaldırır.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6</code></pre>
</div>
</div>
<p>Veri setinde bazı <strong><code>NA</code></strong> değerlerini şimdiden gözlemleyebiliyoruz.</p>
<p>Sonraki adımda, <strong><code>NA</code></strong> değerleri içeren durumları veri setinden kaldırıyoruz.</p>
<ul>
<li><strong><code><a href="https://rdrr.io/r/stats/na.fail.html">na.omit()</a></code> ile Eksik Verileri Çıkarma</strong></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Eksik verileri çıkarma</span></span>
<span><span class="va">airquality_omit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># İlk birkaç satırı görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality_omit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
7    23     299  8.6   65     5   7
8    19      99 13.8   59     5   8</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>İlk çıktıda <strong><code>airquality</code></strong>, eksik değerler (<strong>NA</strong>) hala veri setinde bulunurken, <strong><code>airquality_omit</code></strong> veri setinde eksik değerler içeren satırlar tamamen çıkarılmıştır. Bu, satır sayısının azalmasına yol açar.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Liste bazlı silme">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Liste bazlı silme
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Liste bazlı silme</strong> (Listwise deletion) yöntemi, eksik veriler içeren satırları tamamen kaldırdığı için genellikle birkaç nedenden dolayı tercih edilmez:</p>
<ol type="1">
<li>
<strong>Veri Kaybı</strong>: Eksik değerlere sahip satırların tamamen silinmesi, veri setinin boyutunu küçültür ve bu da analiz için kullanılabilir bilgi miktarını azaltır. Bu durum, özellikle eksik verilerin oranı yüksekse, analiz sonuçlarını ciddi şekilde etkileyebilir.</li>
<li>
<strong>Örnekleme Yanlılığı</strong>: Eksik veriler rastgele (MCAR - Missing Completely at Random) değilse, bu yöntemin kullanımı örneklemde yanlılığa neden olabilir. Sonuç olarak, elde edilen analiz sonuçları tüm veri setini veya popülasyonu doğru bir şekilde temsil etmeyebilir.</li>
<li>
<strong>İstatistiksel Güç Kaybı</strong>: Veri setinin boyutunun küçülmesi, istatistiksel gücü azaltır. Bu da yapılan analizlerin daha az anlamlı sonuçlar üretmesine yol açabilir.</li>
<li>
<strong>Karmaşık Eksiklik Yapıları</strong>: Eksik veriler farklı desenler izleyebilir ve listwise deletion, bu desenleri dikkate almadan tüm eksik satırları kaldırır. Bu, özellikle eksik verilerin analizin anahtar değişkenlerinde olduğu durumlarda önemli bilgilerin kaybolmasına neden olabilir.</li>
</ol>
<p>Bu nedenlerle, eksik verilerle başa çıkmak için <strong>çoklu doldurma (multiple imputation)</strong> veya eksik değerlerin modelleme yöntemleriyle ele alınması gibi daha gelişmiş yöntemler genellikle listwise deletion’a tercih edilir.</p>
</div>
</div>
</section><section id="eksik-verilerin-grafik-olarak-tespiti" class="level3" data-number="6.1.2"><h3 data-number="6.1.2" class="anchored" data-anchor-id="eksik-verilerin-grafik-olarak-tespiti">
<span class="header-section-number">6.1.2</span> Eksik Verilerin Grafik Olarak Tespiti</h3>
<ul>
<li><strong>Eksik Verileri Görselleştirme (<code>naniar</code> Paketinin Kullanımı)</strong></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme (eğer yüklü değilse)</span></span>
<span><span class="co"># install.packages("naniar")</span></span>
<span></span>
<span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verileri görselleştirme</span></span>
<span><span class="fu"><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-gorsellestirme-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Grafik, <strong><code><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss()</a></code></strong> fonksiyonu ile oluşturulmuş ve <strong>airquality</strong> veri setindeki eksik verilerin genel yapısını göstermektedir.</p>
<ul>
<li>
<strong>Siyah alanlar</strong> eksik verileri (<strong>Missing</strong>) temsil ederken, <strong>gri alanlar</strong> mevcut verileri (<strong>Present</strong>) temsil eder.</li>
<li>Ozon değişkeninde %24, Solar.R değişkeninde %5 oranında eksik veri bulunmaktadır. Diğer değişkenler (Wind, Temp, Month, Day) ise eksiksizdir.</li>
</ul>
</blockquote>
<section id="eksik-değerlerin-eşzamanlı-görülmesi" class="level4" data-number="6.1.2.1"><h4 data-number="6.1.2.1" class="anchored" data-anchor-id="eksik-değerlerin-eşzamanlı-görülmesi">
<span class="header-section-number">6.1.2.1</span> Eksik Değerlerin Eşzamanlı Görülmesi</h4>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verilerin UpSet grafiği ile gösterimi</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/gg_miss_upset.html">gg_miss_upset</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-upset-grafigi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><code>gg_miss_upset(airquality)</code> fonksiyonu, <code>naniar</code> paketine ait bir fonksiyondur ve eksik değerlerin birlikteliğini (co-occurrence) görselleştirmek için UpSetR paketini kullanarak bir grafik oluşturur. Bu grafik, hangi değişkenlerin birlikte eksik olduğunu ve bu kombinasyonların ne sıklıkta görüldüğünü gösterir.</p>
<ul>
<li>
<strong>Çubuk grafikler (dikey):</strong> Her bir çubuk, belirli bir eksik değer kombinasyonunu temsil eder. Çubuğun yüksekliği, bu kombinasyonun veri setinde kaç kez tekrarlandığını gösterir.</li>
<li>
<strong>Noktalar ve çizgiler (yatay):</strong> Her bir değişken için bir nokta bulunur. Eğer bir çubukta o değişkenle ilgili nokta doluysa (yani çizgiyle bağlıysa), o kombinasyonda o değişkende eksik değer olduğu anlamına gelir. Örneğin, sadece “<code>Ozone</code>” değişkenine bağlı bir çubuk, sadece “<code>Ozone</code>” değerinin eksik olduğu satırları temsil eder. Hem “<code>Ozone</code>” hem de “<code>Solar.R</code>” değişkenlerine bağlı bir çubuk ise, her iki değişkende de aynı anda eksik değer olan satırları temsil eder.</li>
</ul>
</blockquote>
</section><section id="faktör-düzeyine-göre-veri-eksikliğini-görselleştirme" class="level4" data-number="6.1.2.2"><h4 data-number="6.1.2.2" class="anchored" data-anchor-id="faktör-düzeyine-göre-veri-eksikliğini-görselleştirme">
<span class="header-section-number">6.1.2.2</span> Faktör Düzeyine Göre Veri Eksikliğini Görselleştirme</h4>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verileri faktör düzeyine göre görselleştirme</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/gg_miss_fct.html">gg_miss_fct</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">airquality</span>, fct <span class="op">=</span> <span class="va">Month</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-faktor-duzeyine-gore-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><code>gg_miss_fct(x = airquality, fct = Month)</code> fonksiyonu, <code>naniar</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki eksik verilerin <code>Month</code> değişkenine göre dağılımını görselleştirir. <code>Month</code> burada bir faktör (kategorik değişken) olarak kabul edilir ve her bir ay (5, 6, 7, 8, 9) için ayrı bir çubuk gösterilir.</p>
<p>Grafikte şunlar görülebilir:</p>
<ul>
<li>
<strong>X ekseni (Month):</strong> Ayları temsil eder (5 = Mayıs, 6 = Haziran, …, 9 = Eylül).</li>
<li>
<strong>Y ekseni (Missing Percentage):</strong> Eksik veri yüzdesini temsil eder.</li>
<li>
<strong>Çubuklar:</strong> Her bir ay için bir çubuk bulunur. Çubuğun yüksekliği, o ayda ne kadar eksik veri olduğunu (tüm değişkenler için toplamda) gösterir.</li>
</ul>
<p>Bu grafik, eksik verilerin aylara göre nasıl değiştiğini anlamak için çok faydalıdır. Örneğin, belirli aylarda daha fazla eksik veri olup olmadığını veya eksik verilerin aylara göre bir örüntü izleyip izlemediğini görebilirsiniz. Bu bilgi, veri toplama sürecindeki olası sorunları veya mevsimsel etkileri anlamanıza yardımcı olabilir. Örneğin, eğer belirli bir ayda ölçüm cihazlarında bir arıza olduysa, o ayda daha fazla eksik veri görülebilir.</p>
</blockquote>
<ul>
<li><strong>Eksik Verileri Faktör Düzeyine Göre Nokta Grafiği ile Görselleştirme</strong></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli paketlerin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik veri noktalarını görselleştirme</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Ozone</span>, y <span class="op">=</span> <span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://naniar.njtierney.com/reference/geom_miss_point.html">geom_miss_point</a></span><span class="op">(</span><span class="op">)</span>  <span class="co"># Eksik verileri noktalar olarak görselleştirir</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-faktor-duzeyine-gore-grafik-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="dlookr-paketi-ile-eksik-veriler" class="level4" data-number="6.1.2.3"><h4 data-number="6.1.2.3" class="anchored" data-anchor-id="dlookr-paketi-ile-eksik-veriler">
<span class="header-section-number">6.1.2.3</span> <code>dlookr</code> Paketi ile Eksik Veriler</h4>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme (gerekli fonksiyon için)</span></span>
<span><span class="co"># install.packages("dlookr")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verilerin Pareto grafiği ile gösterimi</span></span>
<span><span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/plot_na_pareto.html">plot_na_pareto</a></span><span class="op">(</span><span class="va">airquality</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-pareto-grafigi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><code>plot_na_pareto(airquality)</code> fonksiyonu, <code>dlookr</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki eksik değerleri bir Pareto grafiği ile görselleştirir.</p>
<ul>
<li>
<strong>X ekseni:</strong> Değişkenleri temsil eder. Değişkenler, eksik değer sayılarına göre en çoktan en aza doğru sıralanmıştır.</li>
<li>
<strong>Sol Y ekseni:</strong> Eksik değer sayısını temsil eder. Her bir değişken için bir çubuk bulunur ve çubuğun yüksekliği o değişkendeki eksik değer sayısını gösterir.</li>
<li>
<strong>Sağ Y ekseni:</strong> Kümülatif eksiklik yüzdesini temsil eder. Çizgi grafiği, değişkenler eklendikçe toplam eksiklik oranının nasıl arttığını gösterir.</li>
</ul>
<p>Pareto grafiği, hangi değişkenlerde en çok eksik değer olduğunu ve bu değişkenlerin toplam eksikliğe ne kadar katkıda bulunduğunu hızlıca anlamak için kullanışlıdır. Genellikle, birkaç değişkenin toplam eksikliğin büyük bir kısmını oluşturduğu görülür (“80/20 kuralı” olarak da bilinir). Bu grafik, eksik verilerle başa çıkarken önceliklerin belirlenmesine yardımcı olabilir. Örneğin, en çok eksik değere sahip değişkenlere odaklanmak, genel eksiklik sorununu çözmek için daha etkili bir yaklaşım olabilir. <code>airquality</code> örneğinde <code>Ozone</code> değişkeninin diğerlerine göre çok daha fazla eksik veriye sahip olduğu kolayca görülebilir.</p>
</blockquote>
<p><strong>Eksik Verilerin Hiyerarşik Kümeleme Grafiği ile Gösterimi <code>dlookr</code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verilerin hiyerarşik kümeleme grafiği ile gösterimi</span></span>
<span><span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/plot_na_hclust.html">plot_na_hclust</a></span><span class="op">(</span><span class="va">airquality</span>, main <span class="op">=</span> <span class="st">"Distribution of missing value"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-hclust-grafigi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li>
<code>plot_na_hclust(airquality, main = "Distribution of missing value")</code> fonksiyonu, <code>dlookr</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki eksik değer örüntülerini hiyerarşik kümeleme (hierarchical clustering) kullanarak görselleştirir.</li>
<li>
<code>main = "Distribution of missing value"</code> argümanı, grafiğe bir başlık ekler.</li>
</ul>
<p>Bu grafik, eksik değerlerin veri setinde rastgele mi dağıldığını yoksa belirli örüntüler izleyip izlemediğini anlamak için çok faydalıdır. Örneğin, belirli satır gruplarının benzer eksik değer örüntülerine sahip olduğunu görmek, veri toplama sürecinde veya verilerin doğasında bir sorun olduğunu gösterebilir. Bu bilgi, eksik verilerle nasıl başa çıkılacağına (örneğin, hangi doldurma yönteminin kullanılacağına) karar verirken önemli bir rol oynayabilir.</p>
</blockquote>
<p><strong>Eksik Verilerin Kesişim Grafiği ile Gösterimi <code>dlookr</code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verilerin kesişim grafiği ile gösterimi</span></span>
<span><span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/plot_na_intersect.html">plot_na_intersect</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/eksik-veri-kesisim-grafigi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><code>plot_na_intersect(airquality)</code> fonksiyonu, <code>dlookr</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki eksik değerlerin kesişimlerini (yani hangi değişkenlerin aynı satırlarda birlikte eksik olduğunu) görselleştirir.</p>
</blockquote>
</section></section><section id="eksik-değerlerin-toplam-sayıları-ve-oranları" class="level3" data-number="6.1.3"><h3 data-number="6.1.3" class="anchored" data-anchor-id="eksik-değerlerin-toplam-sayıları-ve-oranları">
<span class="header-section-number">6.1.3</span> Eksik Değerlerin Toplam Sayıları ve Oranları</h3>
<p><code>n_miss</code> fonksiyonu, verilerdeki tüm <code>NA</code> (yani eksik) değerlerinin toplam sayısını döndürür.</p>
<section id="na-olan-değerlerin-sayısı-için" class="level4" data-number="6.1.3.1"><h4 data-number="6.1.3.1" class="anchored" data-anchor-id="na-olan-değerlerin-sayısı-için">
<span class="header-section-number">6.1.3.1</span> <code>NA</code> olan değerlerin sayısı için:</h4>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik değer sayısını hesaplama</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/n_miss.html">n_miss</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><code>n_miss(airquality)</code> fonksiyonu, <code>naniar</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki toplam eksik değer (NA) sayısını hesaplar. Çıktı olarak <code>[1] 44</code> değeri döner. Bu, <code>airquality</code> veri setinde toplam <strong>44</strong> adet eksik değer olduğunu gösterir.</p>
</blockquote>
</section><section id="na-olmayan-complete-değerlerin-sayısı-için" class="level4" data-number="6.1.3.2"><h4 data-number="6.1.3.2" class="anchored" data-anchor-id="na-olmayan-complete-değerlerin-sayısı-için">
<span class="header-section-number">6.1.3.2</span> <code>NA</code> olmayan (complete) değerlerin sayısı için:</h4>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Tamamlanmış değer sayısını hesaplama</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/n_complete.html">n_complete</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 874</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><code>n_complete(airquality)</code> fonksiyonu, <code>naniar</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki <em>tamamlanmış</em> (yani eksik olmayan) toplam değer sayısını hesaplar. Çıktı olarak <code>[1] 874</code> değeri döner. Bu, <code>airquality</code> veri setinde toplam <strong>874</strong> adet tamamlanmış değer olduğunu gösterir.</p>
</blockquote>
</section><section id="na-olan-değerlerin-oranı-için" class="level4" data-number="6.1.3.3"><h4 data-number="6.1.3.3" class="anchored" data-anchor-id="na-olan-değerlerin-oranı-için">
<span class="header-section-number">6.1.3.3</span> <code>NA</code> olan değerlerin oranı için:</h4>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik değer oranını hesaplama</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/prop_miss.html">prop_miss</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04793028</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><code>prop_miss(airquality)</code> fonksiyonunun çıktısı olan <code>[1] 0.04792626</code>, <code>airquality</code> veri setindeki verilerin yaklaşık <strong>%4.79</strong>’unun eksik olduğunu gösterir. Bu oran, eksik değer sayısının toplam veri noktası sayısına bölünmesiyle bulunur.</p>
</blockquote>
</section><section id="na-olmayan-complete-değerlerin-oranı-için" class="level4" data-number="6.1.3.4"><h4 data-number="6.1.3.4" class="anchored" data-anchor-id="na-olmayan-complete-değerlerin-oranı-için">
<span class="header-section-number">6.1.3.4</span> <code>NA</code> olmayan (complete) değerlerin oranı için:</h4>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># naniar kütüphanesini yükleme</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Tamamlanmış değer oranını hesaplama</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/prop_complete.html">prop_complete</a></span><span class="op">(</span><span class="va">airquality</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9520697</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><code>prop_complete(airquality)</code> fonksiyonu, <code>naniar</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri setindeki <em>tamamlanmış</em> (yani eksik olmayan) değerlerin oranını hesaplar. Çıktı olarak <code>[1] 0.9520737</code> değeri döner. Bu, <code>airquality</code> veri setindeki değerlerin yaklaşık <strong>%95.2</strong>’sinin tamamlanmış olduğunu gösterir.</p>
</blockquote>
</section><section id="eksik-veriler-için-pareto-tablosu-dlookr" class="level4" data-number="6.1.3.5"><h4 data-number="6.1.3.5" class="anchored" data-anchor-id="eksik-veriler-için-pareto-tablosu-dlookr">
<span class="header-section-number">6.1.3.5</span> Eksik veriler için pareto tablosu <code>dlookr</code>
</h4>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme (gerekli fonksiyon için)</span></span>
<span><span class="co"># install.packages("dlookr")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Eksik verilerin Pareto grafiği ile gösterimi</span></span>
<span><span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/plot_na_pareto.html">plot_na_pareto</a></span><span class="op">(</span><span class="va">airquality</span>, </span>
<span>               only_na <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>               <span class="co"># sadece eksik değer içeren değişkenlerin gösterilmesini sağlar.</span></span>
<span>               plot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  variable frequencies  ratio grade cumulative
  &lt;fct&gt;          &lt;int&gt;  &lt;dbl&gt; &lt;fct&gt;      &lt;dbl&gt;
1 Ozone             37 0.242  Bad         84.1
2 Solar.R            7 0.0458 Good       100  </code></pre>
</div>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span>               <span class="co"># grafik yerine sadece tablo çıktısının gösterilmesini sağlar.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="web-raporu-oluşturma" class="level3" data-number="6.1.4"><h3 data-number="6.1.4" class="anchored" data-anchor-id="web-raporu-oluşturma">
<span class="header-section-number">6.1.4</span> Web Raporu Oluşturma</h3>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme </span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span>  </span>
<span></span>
<span><span class="co"># Web raporu oluşturma </span></span>
<span><span class="co"># diagnose_web_report(airquality, subtitle = "airquality")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><code>diagnose_web_report(airquality, subtitle = "airquality")</code> fonksiyonu, <code>dlookr</code> paketine ait bir fonksiyondur ve <code>airquality</code> veri seti için kapsamlı bir veri teşhis raporu oluşturur. Bu rapor bir HTML dosyası olarak kaydedilir ve bir web tarayıcısında görüntülenebilir.</p>
</blockquote>
</section><section id="dlookr-paketi-ile-eksik-değerleri-doldurma" class="level3" data-number="6.1.5"><h3 data-number="6.1.5" class="anchored" data-anchor-id="dlookr-paketi-ile-eksik-değerleri-doldurma">
<span class="header-section-number">6.1.5</span> <code>DLOOKR</code> Paketi ile Eksik Değerleri Doldurma</h3>
<p><strong><code>dlookr</code> paketi ve <code><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na()</a></code></strong></p>
<p><code>dlookr</code> paketi, <strong>veri teşhisi</strong> (<em>data diagnosis</em>) ve <strong>veri keşfi</strong> (<em>data exploration</em>) için tasarlanmış bir R paketidir. Bu paket, veri kalitesini değerlendirmek, veri setini özetlemek, değişkenler arasındaki ilişkileri incelemek ve eksik verilerle başa çıkmak için çeşitli kullanışlı fonksiyonlar içerir. <strong><code><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na()</a></code></strong> fonksiyonu da bu paketin eksik veri yönetimi araçlarından biridir.</p>
<p><code><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na()</a></code> fonksiyonunun temel amacı, bir veri setindeki eksik değerleri (NA) çeşitli yöntemlerle doldurmaktır. Bu fonksiyon, hem sayısal (numeric) hem de kategorik (categorical) değişkenlerdeki eksik değerleri ele alabilir ve farklı doldurma yöntemleri sunar.</p>
<ul>
<li>
<p><strong>Sayısal Değişkenler için Doldurma Yöntemleri:</strong></p>
<ul>
<li>
<code>"mean"</code>: Eksik değerleri değişkenin ortalamasıyla doldurur.</li>
<li>
<code>"median"</code>: Eksik değerleri değişkenin medyanıyla (ortanca) doldurur.</li>
<li>
<code>"mode"</code>: Eksik değerleri değişkenin moduyla (en sık tekrar eden değer) doldurur.</li>
<li>
<code>"knn"</code>: K-en yakın komşu algoritmasını kullanarak eksik değerleri doldurur. Bu yöntem, eksik değerin bulunduğu satıra en yakın olan K tane gözlemi bulur ve bu gözlemlerin değerlerini kullanarak eksik değeri tahmin eder. Bu yöntem için bir referans değişken belirtmek gereklidir.</li>
<li>
<code>"rpart"</code>: Özyinelemeli Bölümleme ve Regresyon Ağaçları (Recursive Partitioning and Regression Trees) yöntemini kullanarak eksik değerleri doldurur. Bu yöntem, bir karar ağacı modeli oluşturarak eksik değerleri tahmin eder. Bu yöntem için bir referans değişken belirtmek gereklidir.</li>
<li>
<code>"mice"</code>: Zincirleme Denklemlerle Çoklu Atama (Multivariate Imputation by Chained Equations) yöntemini kullanarak eksik değerleri doldurur. Bu yöntem, her eksik değişken için bir model oluşturur ve diğer değişkenleri kullanarak eksik değerleri tahmin eder. Bu yöntem için bir referans değişken belirtmek ve bir rastgele sayı başlangıç değeri (random seed) ayarlamak gereklidir.</li>
</ul>
</li>
<li>
<p><strong>Kategorik Değişkenler için Doldurma Yöntemleri:</strong></p>
<ul>
<li>
<code>"mode"</code>: Eksik değerleri değişkenin moduyla (en sık tekrar eden kategori) doldurur.</li>
<li>
<code>"rpart"</code>: Özyinelemeli Bölümleme ve Regresyon Ağaçları yöntemini kullanarak eksik değerleri doldurur. Bu yöntem için bir referans değişken belirtmek gereklidir.</li>
<li>
<code>"mice"</code>: Zincirleme Denklemlerle Çoklu Atama yöntemini kullanarak eksik değerleri doldurur. Bu yöntem için bir referans değişken belirtmek ve bir rastgele sayı başlangıç değeri (random seed) ayarlamak gereklidir.</li>
</ul>
</li>
</ul>
<p><code><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na()</a></code> fonksiyonu, veri ön işleme adımlarında eksik verileri ele almak için kullanışlı bir araçtır. Doldurma yöntemini seçerken, verinizin yapısını ve analizin amacını göz önünde bulundurmanız önemlidir. Örneğin, ortalama ile doldurma, aykırı değerlerden etkilenebilirken, medyan ile doldurma bu etkiyi azaltır. <code>knn</code>, <code>rpart</code> ve <code>mice</code> gibi daha gelişmiş yöntemler ise, değişkenler arasındaki ilişkileri dikkate alarak daha doğru tahminler yapabilir.</p>
<section id="eksik-değer-içeren-sütunu-görüntüleme" class="level4" data-number="6.1.5.1"><h4 data-number="6.1.5.1" class="anchored" data-anchor-id="eksik-değer-içeren-sütunu-görüntüleme">
<span class="header-section-number">6.1.5.1</span> Eksik değer içeren sütunu görüntüleme</h4>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"airquality"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># airquality veri setinin Ozone sütununu görüntüleme</span></span>
<span><span class="va">airquality</span><span class="op">$</span><span class="va">Ozone</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  41  36  12  18  NA  28  23  19   8  NA   7  16  11  14  18  14  34   6
 [19]  30  11   1  11   4  32  NA  NA  NA  23  45 115  37  NA  NA  NA  NA  NA
 [37]  NA  29  NA  71  39  NA  NA  23  NA  NA  21  37  20  12  13  NA  NA  NA
 [55]  NA  NA  NA  NA  NA  NA  NA 135  49  32  NA  64  40  77  97  97  85  NA
 [73]  10  27  NA   7  48  35  61  79  63  16  NA  NA  80 108  20  52  82  50
 [91]  64  59  39   9  16  78  35  66 122  89 110  NA  NA  44  28  65  NA  22
[109]  59  23  31  44  21   9  NA  45 168  73  NA  76 118  84  85  96  78  73
[127]  91  47  32  20  23  21  24  44  21  28   9  13  46  18  13  24  16  13
[145]  23  36   7  14  30  NA  14  18  20</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><code>airquality$Ozone</code> kodu, <code>airquality</code> adlı veri çerçevesinin <code>Ozone</code> adlı sütununu seçer ve bu sütundaki tüm değerleri bir vektör olarak döndürür.</p>
<p>Çıktıda görüldüğü gibi, <code>Ozone</code> sütunu sayısal değerler ve <code>NA</code> (Not Available - Mevcut Değil) değerleri içermektedir. <code>NA</code> değerleri, o gün için ozon ölçümünün yapılamadığını veya kaydedilmediğini gösterir.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Vektör Çıktılarında Köşeli Parantez">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vektör Çıktılarında Köşeli Parantez
</div>
</div>
<div class="callout-body-container callout-body">
<p>Çıktının başında ve sonunda <code>[1]</code>, <code>[28]</code>, <code>[55]</code> gibi ifadeler bulunur. Bunlar, çıktının hangi indeksinden itibaren yeni bir satıra geçildiğini gösterir. Örneğin, <code>[28]</code> ifadesi, o satırda 28. elemandan itibaren değerlerin listelendiğini belirtir. Bu, çıktının daha okunabilir olmasını sağlar, özellikle de çok uzun vektörler görüntülendiğinde.</p>
</div>
</div>
</blockquote>
</section><section id="eksik-değerleri-ortalama-mean-ile-doldurma" class="level4" data-number="6.1.5.2"><h4 data-number="6.1.5.2" class="anchored" data-anchor-id="eksik-değerleri-ortalama-mean-ile-doldurma">
<span class="header-section-number">6.1.5.2</span> Eksik değerleri ortalama (<code>mean</code>) ile doldurma</h4>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># dlookr kütüphanesini yükleme </span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone değişkenini Temp i referans alarak ortalama ile doldurma</span></span>
<span><span class="va">aq_imp_ozone_mean</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="va">Ozone</span>, <span class="va">Temp</span>, method <span class="op">=</span> <span class="st">"mean"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># SADECE Ozone sütununu görüntüleme</span></span>
<span><span class="va">aq_imp_ozone_mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  41.00000  36.00000  12.00000  18.00000  42.12931  28.00000  23.00000
  [8]  19.00000   8.00000  42.12931   7.00000  16.00000  11.00000  14.00000
 [15]  18.00000  14.00000  34.00000   6.00000  30.00000  11.00000   1.00000
 [22]  11.00000   4.00000  32.00000  42.12931  42.12931  42.12931  23.00000
 [29]  45.00000 115.00000  37.00000  42.12931  42.12931  42.12931  42.12931
 [36]  42.12931  42.12931  29.00000  42.12931  71.00000  39.00000  42.12931
 [43]  42.12931  23.00000  42.12931  42.12931  21.00000  37.00000  20.00000
 [50]  12.00000  13.00000  42.12931  42.12931  42.12931  42.12931  42.12931
 [57]  42.12931  42.12931  42.12931  42.12931  42.12931 135.00000  49.00000
 [64]  32.00000  42.12931  64.00000  40.00000  77.00000  97.00000  97.00000
 [71]  85.00000  42.12931  10.00000  27.00000  42.12931   7.00000  48.00000
 [78]  35.00000  61.00000  79.00000  63.00000  16.00000  42.12931  42.12931
 [85]  80.00000 108.00000  20.00000  52.00000  82.00000  50.00000  64.00000
 [92]  59.00000  39.00000   9.00000  16.00000  78.00000  35.00000  66.00000
 [99] 122.00000  89.00000 110.00000  42.12931  42.12931  44.00000  28.00000
[106]  65.00000  42.12931  22.00000  59.00000  23.00000  31.00000  44.00000
[113]  21.00000   9.00000  42.12931  45.00000 168.00000  73.00000  42.12931
[120]  76.00000 118.00000  84.00000  85.00000  96.00000  78.00000  73.00000
[127]  91.00000  47.00000  32.00000  20.00000  23.00000  21.00000  24.00000
[134]  44.00000  21.00000  28.00000   9.00000  13.00000  46.00000  18.00000
[141]  13.00000  24.00000  16.00000  13.00000  23.00000  36.00000   7.00000
[148]  14.00000  30.00000  42.12931  14.00000  18.00000  20.00000
attr(,"var_type")
[1] "numerical"
attr(,"method")
[1] "mean"
attr(,"na_pos")
 [1]   5  10  25  26  27  32  33  34  35  36  37  39  42  43  45  46  52  53  54
[20]  55  56  57  58  59  60  61  65  72  75  83  84 102 103 107 115 119 150
attr(,"type")
[1] "missing values"
attr(,"message")
[1] "complete imputation"
attr(,"success")
[1] TRUE
attr(,"class")
[1] "imputation" "numeric"   </code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li>
<code>data</code>: İşlem yapılacak veri seti. Burada <code>airquality</code> veri seti kullanılmıştır.</li>
<li>
<code>target</code>: Eksik değerlerin doldurulacağı sütun. Burada <code>Ozone</code> sütunu belirtilmiştir.</li>
<li>
<code>ref</code>: Referans alınacak sütun. Burada <code>Temp</code> sütunu kullanılmıştır.</li>
<li>
<code>method</code>: Doldurma yöntemi. <code>"mean"</code> ile ortalama kullanılarak doldurma yapılır.</li>
</ul>
<p><strong>Çalışma Prensibi:</strong> Eksik değerler <code>Temp</code> sütununun ortalamasına göre doldurulmuş ve yeni bir veri seti (<code>aq_imp_ozone</code>) oluşturulmuştur.</p>
</blockquote>
</section><section id="ortalama-mean-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları" class="level4" data-number="6.1.5.3"><h4 data-number="6.1.5.3" class="anchored" data-anchor-id="ortalama-mean-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları">
<span class="header-section-number">6.1.5.3</span> Ortalama (<code>mean</code>) ile doldurma öncesi ve sonrası yoğunluk dağılımları</h4>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aq_imp_ozone_mean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/imputed-ozone-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Eksik değerlerin ortalama ile doldurulması, veri setinin genel dağılımında hafif değişikliklere yol açmıştır. Eksik değerlerin doldurulması, yoğunluk eğrisini daha düzgün hale getirmiştir, ancak bu işlem, verilerin doğal dağılımını biraz değiştirebilir. Özellikle veri çok eksikse, ortalama ile doldurma yöntemi dağılımın şeklini etkileyebilir. Eğer veri setinin doğal varyasyonunu korumak çok önemliyse, alternatif doldurma yöntemleri (örneğin, <code>knn</code> veya regresyon tabanlı yöntemler) düşünülebilir.</p>
</blockquote>
</section><section id="medyan-median-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları" class="level4" data-number="6.1.5.4"><h4 data-number="6.1.5.4" class="anchored" data-anchor-id="medyan-median-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları">
<span class="header-section-number">6.1.5.4</span> Medyan (<code>median</code>) ile doldurma öncesi ve sonrası yoğunluk dağılımları</h4>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone ve Temp değişkenlerini medyan ile doldurma</span></span>
<span><span class="va">aq_imp_ozone_median</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="va">Ozone</span>, <span class="va">Temp</span>, method <span class="op">=</span> <span class="st">"median"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># plot() fonksiyonu ile çizim (indekse karşı değer grafiği)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aq_imp_ozone_median</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/imputed-ozone-median-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Grafikte, x ekseni vektördeki elemanların sırasını (indeks), y ekseni ise medyan ile doldurulmuş <code>Ozone</code> değerlerini gösterir. Ortalama ile doldurmaya benzer şekilde, grafikte noktaların rastgele yukarı aşağı hareket ettiğini görürsünüz. Ancak, medyan ile doldurmada, ortalama ile doldurmaya kıyasla grafikte daha az yatay çizgi veya düz bölge görürsünüz. Bunun nedeni, medyanın ortalamadan farklı değerlere sahip olabilmesi ve aynı değerin daha az tekrar etmesidir.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled" title="Ortalama vs. Medyan ile Eksik Değer Doldurma">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ortalama vs.&nbsp;Medyan ile Eksik Değer Doldurma
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ortalama ile doldurma, dağılımın ortasında bir yığılmaya neden olurken, medyan ile doldurma bu yığılmayı daha az belirgin hale getirir. Çünkü medyan, aykırı değerlerden ortalamaya göre daha az etkilenir. Bu nedenle, verilerinizde aykırı değerler varsa, medyan ile doldurma ortalama ile doldurmaya göre daha iyi bir seçenek olabilir.</p>
</div>
</div>
</section><section id="knn-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları" class="level4" data-number="6.1.5.5"><h4 data-number="6.1.5.5" class="anchored" data-anchor-id="knn-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları">
<span class="header-section-number">6.1.5.5</span> <code>knn</code> ile doldurma öncesi ve sonrası yoğunluk dağılımları</h4>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone değişkenini knn ile doldurma (Temp'i referans değişken olarak kullanır)</span></span>
<span><span class="va">aq_imp_ozone_knn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="va">Ozone</span>, <span class="va">Temp</span>, method <span class="op">=</span> <span class="st">"knn"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># plot() fonksiyonu ile çizim (indekse karşı değer grafiği)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aq_imp_ozone_knn</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/imputed-ozone-knn-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Yukarıdaki kod, <code>Ozone</code> değişkenindeki eksik değerleri <strong><em>knn</em></strong> <strong>(k-Nearest Neighbors - k-En Yakın Komşu)</strong> yöntemiyle dolduruyor ve ardından bu doldurulmuş değerleri <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> fonksiyonu ile çiziliyor.</p>
<ul>
<li>
<strong>Referans Değişkenin Önemi:</strong> knn ile doldurma yaparken, seçilen referans değişkenin (burada <code>Temp</code>) eksik değerlere sahip olmaması veya çok az eksik değere sahip olması önemlidir. Aksi takdirde, modelin doğruluğu düşebilir.</li>
<li>
<strong>Benzer Gözlemler:</strong> knn, eksik değere sahip olan gözleme en benzer k tane gözlemi bulur ve bu gözlemlerin değerlerini kullanarak eksik değeri tahmin eder. Bu nedenle, verideki yerel örüntüleri yakalamada etkilidir.</li>
<li>
<strong>k Değeri:</strong> k parametresi (komşu sayısı) önemlidir. Çok küçük bir k değeri, aşırı uyuma (overfitting) neden olabilirken, çok büyük bir k değeri, yerel örüntüleri kaçırmaya neden olabilir. <code><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na()</a></code> fonksiyonunda k değeri varsayılan olarak 5’tir, ancak gerekirse değiştirilebilir.</li>
<li>
<strong>Dağılımın Değişimi:</strong> knn ile doldurma, ortalama veya medyan ile doldurmaya göre dağılımı daha az etkiler. Çünkü bu yöntem, eksik değerleri tek bir sabit değerle doldurmak yerine, benzer gözlemlerin değerlerine göre farklı değerlerle doldurur.</li>
</ul>
</blockquote>
</section><section id="rpart-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları" class="level4" data-number="6.1.5.6"><h4 data-number="6.1.5.6" class="anchored" data-anchor-id="rpart-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları">
<span class="header-section-number">6.1.5.6</span> <code>rpart</code> ile doldurma öncesi ve sonrası yoğunluk dağılımları</h4>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone değişkenini rpart ile doldurma (Temp'i referans değişken olarak kullanır)</span></span>
<span><span class="va">aq_imp_ozone_rpart</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="va">Ozone</span>, <span class="va">Temp</span>, method <span class="op">=</span> <span class="st">"rpart"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># plot() fonksiyonu ile çizim (indekse karşı değer grafiği)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aq_imp_ozone_rpart</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/imputed-ozone-rpart-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Yukarıdaki kod ile <code>Ozone</code> değişkenindeki eksik değerleri <strong><em>rpart</em></strong> <strong>(Recursive Partitioning and Regression Trees - Özyinelemeli Bölümleme ve Regresyon Ağaçları)</strong> yöntemiyle dolduruyor ve ardından bu doldurulmuş değerleri <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> fonksiyonu ile çiziyor.</p>
<ul>
<li>
<strong>referans Değişkenin Önemi:</strong> rpart ile doldurma yaparken, seçilen referans değişkenin (burada <code>Temp</code>) eksik değerlere sahip olmaması veya çok az eksik değere sahip olması önemlidir. Aksi takdirde, modelin doğruluğu düşebilir.</li>
<li>
<strong>Doğrusal Olmayan İlişkiler:</strong> rpart, değişkenler arasındaki doğrusal olmayan ilişkileri de yakalayabildiği için, ortalama veya medyan ile doldurmaya göre daha doğru sonuçlar verebilir. Ancak, aşırı uyum (overfitting) riskini de beraberinde getirebilir.</li>
<li>
<strong>Dağılımın Değişimi:</strong> rpart ile doldurma, ortalama veya medyan ile doldurmaya göre dağılımı daha az etkiler. Çünkü bu yöntem, eksik değerleri tek bir sabit değerle doldurmak yerine, referans değişkene göre farklı değerlerle doldurur.</li>
</ul>
</blockquote>
</section><section id="mice-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları" class="level4" data-number="6.1.5.7"><h4 data-number="6.1.5.7" class="anchored" data-anchor-id="mice-ile-doldurma-öncesi-ve-sonrası-yoğunluk-dağılımları">
<span class="header-section-number">6.1.5.7</span> <code>mice</code> ile doldurma öncesi ve sonrası yoğunluk dağılımları</h4>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone değişkenini mice ile doldurma (Temp'i ve diğer değişkenleri kullanır)</span></span>
<span><span class="va">aq_imp_ozone_mice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="va">Ozone</span>, <span class="va">Temp</span>, </span>
<span>                                 method <span class="op">=</span> <span class="st">"mice"</span>, </span>
<span>                                 seed <span class="op">=</span> <span class="fl">111</span>, </span>
<span>                                 print <span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># plot() fonksiyonu ile çizim (indekse karşı değer grafiği)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">aq_imp_ozone_mice</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="veri_temizleme_files/figure-html/imputed-ozone-mice-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Yukarıdaki kod ile <code>Ozone</code> değişkenindeki eksik değerleri <em>mice</em> (Multivariate Imputation by Chained Equations - Zincirleme Denklemlerle Çoklu Atama) yöntemiyle dolduruyor ve ardından bu doldurulmuş değerleri <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> fonksiyonu ile çiziyor.</p>
<ul>
<li>
<strong>Çoklu Atama:</strong> <code>mice</code>, eksik değerler için birden fazla olası değer ürettiği için, eksik verilerin belirsizliğini daha iyi yansıtır. Bu, daha doğru ve güvenilir sonuçlar elde etmenizi sağlar.</li>
<li>
<strong>Değişkenler Arası İlişkiler:</strong> <code>mice</code>, değişkenler arasındaki ilişkileri dikkate aldığı için, diğer yöntemlere göre daha iyi tahminler yapabilir.</li>
<li>
<strong>Dağılımın Korunması:</strong> <code>mice</code>, verinin orijinal dağılımını daha iyi korur. Ortalama veya medyan ile doldurma, dağılımda bozulmalara neden olabilirken, <code>mice</code> bu etkiyi en aza indirir.</li>
</ul>
</blockquote>
</section><section id="doldurulmuş-veriyi-orijinal-veriye-entegre-etme---aşama-1" class="level4" data-number="6.1.5.8"><h4 data-number="6.1.5.8" class="anchored" data-anchor-id="doldurulmuş-veriyi-orijinal-veriye-entegre-etme---aşama-1">
<span class="header-section-number">6.1.5.8</span> Doldurulmuş veriyi orijinal veriye entegre etme - Aşama 1</h4>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanelerin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Orijinal veri setini kopyalama</span></span>
<span><span class="va">airquality_imp</span> <span class="op">&lt;-</span> <span class="va">airquality</span></span>
<span></span>
<span><span class="co"># Doldurulmuş Ozone verisini orijinal veri setine atama</span></span>
<span><span class="va">airquality_imp</span><span class="op">$</span><span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="va">aq_imp_ozone_mice</span></span>
<span></span>
<span><span class="co"># Doldurulmuş veri setini görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality_imp</span>, <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Ozone Solar.R Wind Temp Month Day
1   41.0     190  7.4   67     5   1
2   36.0     118  8.0   72     5   2
3   12.0     149 12.6   74     5   3
4   18.0     313 11.5   62     5   4
5   21.0      NA 14.3   56     5   5
6   28.0      NA 14.9   66     5   6
7   23.0     299  8.6   65     5   7
8   19.0      99 13.8   59     5   8
9    8.0      19 20.1   61     5   9
10  40.2     194  8.6   69     5  10</code></pre>
</div>
</div>
</section><section id="doldurulmuş-veriyi-orijinal-veriye-entegre-etme---aşama-2" class="level4" data-number="6.1.5.9"><h4 data-number="6.1.5.9" class="anchored" data-anchor-id="doldurulmuş-veriyi-orijinal-veriye-entegre-etme---aşama-2">
<span class="header-section-number">6.1.5.9</span> Doldurulmuş veriyi orijinal veriye entegre etme - Aşama 2</h4>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanelerin yüklenmesi</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/choonghyunryu/dlookr/">dlookr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ozone değişkenini ortalama ile doldurma</span></span>
<span><span class="va">aq_imp_solar_mice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://choonghyunryu.github.io/dlookr/reference/imputate_na.html">imputate_na</a></span><span class="op">(</span><span class="va">airquality_imp</span>, <span class="va">Solar.R</span>, <span class="va">Temp</span>, </span>
<span>                                 method <span class="op">=</span> <span class="st">"mice"</span>, </span>
<span>                                 seed <span class="op">=</span> <span class="fl">111</span>,</span>
<span>                                 print <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># "print =" argümanı eğer TRUE olarak ayarlanırsa, mice işlemin geçmişini konsolda</span></span>
<span><span class="co"># yazdıracaktır. Sessiz bir hesaplama için print=FALSE kullanın.</span></span>
<span></span>
<span><span class="co"># Doldurulmuş Ozone verisini orijinal veri setine atama</span></span>
<span><span class="va">airquality_imp</span><span class="op">$</span><span class="va">Solar.R</span> <span class="op">&lt;-</span> <span class="va">aq_imp_solar_mice</span></span>
<span></span>
<span><span class="co"># Doldurulmuş veri setini görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality_imp</span>, <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Ozone Solar.R Wind Temp Month Day
1   41.0   190.0  7.4   67     5   1
2   36.0   118.0  8.0   72     5   2
3   12.0   149.0 12.6   74     5   3
4   18.0   313.0 11.5   62     5   4
5   21.0   266.2 14.3   56     5   5
6   28.0   218.0 14.9   66     5   6
7   23.0   299.0  8.6   65     5   7
8   19.0    99.0 13.8   59     5   8
9    8.0    19.0 20.1   61     5   9
10  40.2   194.0  8.6   69     5  10</code></pre>
</div>
</div>
<p><strong>Orijinal veri seti ile karşılaştırma</strong></p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Ozone Solar.R Wind Temp Month Day
1     41     190  7.4   67     5   1
2     36     118  8.0   72     5   2
3     12     149 12.6   74     5   3
4     18     313 11.5   62     5   4
5     NA      NA 14.3   56     5   5
6     28      NA 14.9   66     5   6
7     23     299  8.6   65     5   7
8     19      99 13.8   59     5   8
9      8      19 20.1   61     5   9
10    NA     194  8.6   69     5  10</code></pre>
</div>
</div>
</section></section><section id="mice-paketi-ile-eksik-değerleri-doldurma" class="level3" data-number="6.1.6"><h3 data-number="6.1.6" class="anchored" data-anchor-id="mice-paketi-ile-eksik-değerleri-doldurma">
<span class="header-section-number">6.1.6</span> <code>MICE</code> Paketi ile Eksik Değerleri Doldurma</h3>
<p>MICE paketi, eksik veri problemini çözmek için kullanılan bir araçtır ve eksik verileri çoklu imputasyon yöntemini kullanarak işleme alır. Süreç, eksik veri içeren bir veri setiyle başlar. Bu veri genellikle bir data frame formatındadır ve eksik verilerin, diğer değişkenlerle olan ilişkilerine dayanarak doldurulması hedeflenir.</p>
<p>MICE paketi, eksik veri problemini çözmek için şu adımları takip eder:</p>
<ol type="1">
<li>
<p><strong>Eksik verileri birden fazla doldurur (<code><a href="https://amices.org/mice/reference/mice.html">mice()</a></code>).</strong></p>
<p>İlk adımda, <code><a href="https://amices.org/mice/reference/mice.html">mice()</a></code> fonksiyonu kullanılarak eksik veriler birden fazla iterasyonla doldurulur. Her iterasyonda eksik olan değişkenler, diğer değişkenlerle olan ilişkileri kullanılarak tahmin edilir. Bu işlem sonucunda, doldurulmuş veri setlerini içeren bir “mids” nesnesi oluşturulur.</p>
</li>
<li>
<p><strong>Doldurulan veri setleri üzerinde analizler yapar (<code><a href="https://rdrr.io/r/base/with.html">with()</a></code>).</strong></p>
<p>Daha sonra, <code><a href="https://rdrr.io/r/base/with.html">with()</a></code> fonksiyonu aracılığıyla doldurulan veri setleri üzerinde istatistiksel analizler gerçekleştirilir. Örneğin, her doldurulmuş veri seti için regresyon analizi gibi istatistiksel işlemler yapılabilir ve bu analizlerin sonuçları “mira” nesnesi olarak saklanır.</p>
</li>
<li>
<p><strong>Analiz sonuçlarını havuzlar ve birleştirir (<code><a href="https://amices.org/mice/reference/pool.html">pool()</a></code>).</strong></p>
<p>Son aşamada, <code><a href="https://amices.org/mice/reference/pool.html">pool()</a></code> fonksiyonu kullanılarak her bir doldurulmuş veri seti üzerinde yapılan analizlerin sonuçları birleştirilir. Bu birleştirme işlemi, eksik veri kaynaklı belirsizliği hesaba katarak daha güvenilir ve tutarlı sonuçlar elde etmeyi sağlar. Bu süreç sonucunda, analizlerin nihai sonuçları “mipo” nesnesi olarak elde edilir.</p>
</li>
</ol>
<p>MICE paketi, eksik veri problemini istatistiksel olarak en iyi şekilde ele alarak analizlerin güvenilirliğini artırmayı hedefler ve eksik veriden kaynaklanan yanlılığı azaltır.</p>
<p><a href="https://www.jstatsoft.org/article/view/v045i03"><img src="images/mice.png" class="img-fluid"></a></p>
<p>Figür: <a href="https://www.jstatsoft.org/article/view/v045i03" class="uri">https://www.jstatsoft.org/article/view/v045i03</a></p>
<p><strong>Veri Seti <code>nhanes</code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Gerekli kütüphanelerin yüklenmesi</span></span>
<span><span class="co"># install.packages("mice")</span></span>
<span><span class="co"># install.packages("tidyverse")</span></span>
<span><span class="co"># install.packages("NHANES")</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">NHANES</span><span class="op">)</span></span>
<span></span>
<span><span class="va">nhanes3</span> <span class="op">&lt;-</span> <span class="va">NHANES</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>   <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">Weight</span>, <span class="va">Height</span>, <span class="va">TotChol</span>, <span class="va">PhysActive</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># NHANES veri setinin görüntülenmesi (örnek olarak ilk 10 satır)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">nhanes3</span>, <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   Weight Height TotChol PhysActive
    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;     
 1   87.4   165.    3.49 No        
 2   87.4   165.    3.49 No        
 3   87.4   165.    3.49 No        
 4   17     105.   NA    &lt;NA&gt;      
 5   86.7   168.    6.7  No        
 6   29.8   133.    4.86 &lt;NA&gt;      
 7   35.2   131.    4.09 &lt;NA&gt;      
 8   75.7   167.    5.82 Yes       
 9   75.7   167.    5.82 Yes       
10   75.7   167.    5.82 Yes       </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong><code>nhanes</code> Veri Seti</strong></p>
<p>NHANES (Ulusal Sağlık ve Beslenme İnceleme Anketi), ABD’de yetişkinlerin ve çocukların sağlık ve beslenme durumunu ölçen bir CDC araştırmasıdır. Anketler ve fiziksel muayeneler içerir. 76 farklı değişkeni bulunmaktadır. Araştırmamızda özellikle aşağıda yer alan</p>
<p>Çalışmamızda aşağıda yer alan değişkenlere odaklanılacaktır:</p>
<ul>
<li>
<strong>Weight (Kilo):</strong> Obezite ve aşırı kiloyu değerlendirmek için ölçülür.</li>
<li>
<strong>Height (Boy):</strong> VKİ (Vücut Kitle İndeksi) hesaplamak için kullanılır.</li>
<li>
<strong>TotChol (Toplam Kolesterol):</strong> Kalp hastalığı riskini gösterir.</li>
<li>
<strong>PhysActive (Fiziksel Aktivite):</strong> Genel sağlık için önemlidir.</li>
</ul>
<p>Bu veriler, halk sağlığı sorunlarını anlamak ve sağlık politikalarını değerlendirmek için kullanılır.</p>
</blockquote>
<p><strong><code>nhanes</code> Veri Setinde Eksik Değerler Özet Tablosu</strong></p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/njtierney/naniar">naniar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># miss_var_summary() fonksiyonunu uygulama</span></span>
<span><span class="fu"><a href="https://naniar.njtierney.com/reference/miss_var_summary.html">miss_var_summary</a></span><span class="op">(</span><span class="va">nhanes3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  variable   n_miss pct_miss
  &lt;chr&gt;       &lt;int&gt;    &lt;num&gt;
1 PhysActive   1674    16.7 
2 TotChol      1526    15.3 
3 Height        353     3.53
4 Weight         78     0.78</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li>
<strong><code>PhysActive 167 16.7</code>:</strong> <code>PhysActive</code> değişkeninde 167 eksik veri vardır ve bu, toplam verinin %16.7’sine karşılık gelir.</li>
<li>
<strong><code>TotChol 152 15.3</code>:</strong> <code>TotChol</code> değişkeninde 152 eksik veri vardır ve bu, toplam verinin %15.3’üne karşılık gelir.</li>
<li>
<strong><code>Height 35 3.53</code>:</strong> <code>Height</code> değişkeninde 35 eksik veri vardır ve bu, toplam verinin %3.53’üne karşılık gelir.</li>
<li>
<strong><code>Weight 7 0.78</code>:</strong> <code>Weight</code> değişkeninde 7 eksik veri vardır ve bu, toplam verinin %0.78’ine karşılık gelir.</li>
</ul>
</blockquote>
<section id="mice-çoklu-imputasyon-ile-eksik-veri-doldurma" class="level4" data-number="6.1.6.1"><h4 data-number="6.1.6.1" class="anchored" data-anchor-id="mice-çoklu-imputasyon-ile-eksik-veri-doldurma">
<span class="header-section-number">6.1.6.1</span> MICE (Çoklu İmputasyon) ile Eksik Veri Doldurma</h4>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># nhanes veri setinde eksik değerleri doldurma (20 imputasyon seti oluşturma)</span></span>
<span><span class="va">nhanes_multiimp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://amices.org/mice/reference/mice.html">mice</a></span><span class="op">(</span><span class="va">nhanes3</span>, m <span class="op">=</span> <span class="fl">20</span>, print <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Bu kod, <code>mice</code> paketi kullanılarak <strong>nhanes</strong> veri setindeki eksik değerlerin doldurulması için çoklu imputasyon işlemi gerçekleştirir. Burada, <code>m = 20</code> parametresiyle eksik değerlerin 20 farklı tahmini yapılır ve her biri bir imputasyon veri seti olarak oluşturulur.</p>
<ul>
<li>
<code>nhanes</code>: İçerisinde eksik değerler bulunan örnek bir veri seti.</li>
<li>
<code>m = 20</code>: Çoklu imputasyon işlemiyle 20 farklı doldurulmuş veri seti oluşturulacağını belirtir.</li>
</ul>
<p>Yukarıdaki kod, <code>mice</code> paketini kullanarak <code>nhanes</code> veri setindeki eksik değerleri çoklu atama yöntemiyle doldurur. Bu yöntem, eksik verilerin belirsizliğini hesaba katarak daha doğru ve güvenilir analizler yapmanıza olanak tanır. Kodun doğru çalışması için <code>data(nhanes)</code> satırının eklenmesi önemlidir. Ayrıca, <code>seed</code> eklenmesi, sonuçların tekrarlanabilirliğini sağlar. Kod, <code>nhanes_multiimp</code> adında bir <code>mids</code> nesnesi oluşturur.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Çoklu Atama ve mice'ın Avantajları">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Çoklu Atama ve mice’ın Avantajları
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<strong>Çoklu Atama:</strong> <code>mice</code>, eksik değerler için tek bir değer yerine birden fazla olası değer ürettiği için, eksik verilerin belirsizliğini daha iyi yansıtır. Bu, standart tek atama yöntemlerine (ortalama, medyan vb.) göre daha doğru ve güvenilir sonuçlar elde etmenizi sağlar. Tek bir değer atamak yerine, olası değerlerin bir dağılımını kullanarak, eksik veriden kaynaklanan belirsizliği modelinize dahil edersiniz.</li>
<li>
<strong>Değişkenler Arası İlişkiler:</strong> <code>mice</code>, atama işlemi sırasında değişkenler arasındaki ilişkileri dikkate alır. Bu, eksik verilerin daha gerçekçi ve tutarlı bir şekilde tahmin edilmesini sağlar. Örneğin, yaş ve VKİ arasındaki ilişkiyi göz önünde bulundurarak, eksik VKİ değerlerini daha doğru bir şekilde tahmin edebilir.</li>
<li>
<strong>Dağılımın Korunması:</strong> <code>mice</code>, verinin orijinal dağılımını daha iyi korur. Ortalama veya medyan ile doldurma gibi basit yöntemler, veri dağılımında bozulmalara neden olabilirken, <code>mice</code> bu etkiyi en aza indirir. Bu, analizlerinizin daha güvenilir ve anlamlı olmasını sağlar.</li>
</ul>
</div>
</div>
</section><section id="mice-ile-veri-setleri-üzerinde-lineer-regresyon-modeli-kurma" class="level4" data-number="6.1.6.2"><h4 data-number="6.1.6.2" class="anchored" data-anchor-id="mice-ile-veri-setleri-üzerinde-lineer-regresyon-modeli-kurma">
<span class="header-section-number">6.1.6.2</span> MICE ile Veri Setleri Üzerinde Lineer Regresyon Modeli Kurma</h4>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Her bir atanmış veri setine lineer regresyon modeli uygula</span></span>
<span><span class="va">lm_multiimp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">nhanes_multiimp</span>, <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Weight</span> <span class="op">~</span> <span class="va">Height</span> <span class="op">+</span> <span class="va">TotChol</span> <span class="op">+</span> <span class="va">PhysActive</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Bu kod, daha önce oluşturulan <code>nhanes_multiimp</code> adlı <code>mids</code> (multiple imputation data set) nesnesini kullanarak, her bir tamamlanmış veri setine bir lineer regresyon modeli uygular.</p>
<ul>
<li><p><strong><code>with(nhanes_multiimp, ...)</code>:</strong> Bu fonksiyon, <code>nhanes_multiimp</code> nesnesindeki <em>her bir</em> tamamlanmış veri seti üzerinde belirtilen ifadeyi uygular. Yani, 20 farklı tamamlanmış veri setin varsa, bu ifade 20 kez çalıştırılır ve her biri için ayrı bir lineer regresyon modeli oluşturulur.</p></li>
<li><p><strong><code>lm(Weight ~ Height + TotChol + PhysActive)</code>:</strong> Bu, lineer regresyon modelini tanımlar. <code>Weight</code> (Kilo) bağımlı değişken, <code>Height</code> (Boy), <code>TotChol</code> (Toplam Kolesterol) ve <code>PhysActive</code> (Fiziksel Aktivite) ise bağımsız değişkenlerdir. Yani, kilonun boy, toplam kolesterol ve fiziksel aktivite ile nasıl ilişkili olduğunu inceliyoruz.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Faktör Dönüşümü">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Faktör Dönüşümü
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>PhysActive’in Faktöre Dönüştürülmesi</strong>: Eğer PhysActive değişkeni sayısal olarak kodlanmış bir kategorik değişken ise (örneğin, 1=Aktif, 2=Pasif ya da yes, no gibi), lineer regresyon modelinde doğru şekilde yorumlanabilmesi için bu değişkeni <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> fonksiyonu ile faktöre dönüştürmek çok önemlidir. Kodu bu duruma göre güncelledim. Eğer <code>PhysActive</code> zaten bir faktör ise bu satıra gerek yoktur.</p>
</div>
</div>
</blockquote>
</section><section id="mice-ile-regresyon-sonuçlarını-havuzlama" class="level4" data-number="6.1.6.3"><h4 data-number="6.1.6.3" class="anchored" data-anchor-id="mice-ile-regresyon-sonuçlarını-havuzlama">
<span class="header-section-number">6.1.6.3</span> MICE ile Regresyon Sonuçlarını Havuzlama</h4>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Çoklu imputasyon veri setleri üzerindeki regresyon sonuçlarını havuzlama</span></span>
<span><span class="va">lm_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://amices.org/mice/reference/pool.html">pool</a></span><span class="op">(</span><span class="va">lm_multiimp</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Havuzlanmış sonuçları özetleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_pooled</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           term    estimate  std.error  statistic         df      p.value
1   (Intercept) -93.2761794 1.88249998 -49.549100   85.53417 9.001161e-65
2        Height   0.9997873 0.01088186  91.876490   92.25780 1.680034e-92
3       TotChol   1.5587611 0.17765159   8.774259 2354.76828 3.236133e-18
4 PhysActiveYes  -5.9132808 0.38186334 -15.485332 1660.16326 1.265237e-50</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Bu kod, <code>lm_multiimp</code> nesnesindeki çoklu imputasyon veri setleri üzerinde oluşturulan lineer regresyon modellerinin sonuçlarını birleştirir (pool). Havuzlama işlemi, eksik veriler nedeniyle ortaya çıkan belirsizliği hesaba katar ve tüm imputasyon veri setlerinden elde edilen sonuçları birleştirerek daha doğru ve güvenilir tahminler sunar.</p>
<p>Bu model, bağımlı değişken olan <strong>Weight (Ağırlık)</strong> üzerinde <strong>Height (Boy Uzunluğu)</strong>, <strong>TotChol (Toplam Kolesterol)</strong> ve <strong>PhysActive (Fiziksel Aktivite Durumu)</strong> değişkenlerinin etkilerini anlamlı bir şekilde açıklamaktadır. <strong>Tüm değişkenlerin p-değerleri oldukça küçüktür ve bu değişkenlerin modelde anlamlı bir etkisi olduğunu göstermektedir.</strong> Modeldeki katsayılar, bağımlı değişken üzerinde her bir bağımsız değişkenin etkisini istatistiksel olarak güçlü bir şekilde temsil etmektedir.</p>
</blockquote>
</section><section id="mice-ile-tamamlanmış-veri-seti" class="level4" data-number="6.1.6.4"><h4 data-number="6.1.6.4" class="anchored" data-anchor-id="mice-ile-tamamlanmış-veri-seti">
<span class="header-section-number">6.1.6.4</span> MICE ile Tamamlanmış Veri Seti</h4>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># İlk doldurulmuş veri setini elde etme</span></span>
<span><span class="va">nhanes3_completed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/complete.html">complete</a></span><span class="op">(</span><span class="va">nhanes_multiimp</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Doldurulmuş veri setini görüntüleme</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">nhanes3_completed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Weight Height TotChol PhysActive
1   87.4  164.7    3.49         No
2   87.4  164.7    3.49         No
3   87.4  164.7    3.49         No
4   17.0  105.4    3.80         No
5   86.7  168.4    6.70         No
6   29.8  133.1    4.86        Yes</code></pre>
</div>
</div>
</section><section id="ham-veri-ile-son-veriyi-karşılaştırma" class="level4" data-number="6.1.6.5"><h4 data-number="6.1.6.5" class="anchored" data-anchor-id="ham-veri-ile-son-veriyi-karşılaştırma">
<span class="header-section-number">6.1.6.5</span> Ham Veri ile Son Veriyi Karşılaştırma</h4>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">nhanes3_completed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Weight           Height         TotChol       PhysActive
 Min.   :  2.80   Min.   : 83.6   Min.   : 1.530   No :4710  
 1st Qu.: 56.10   1st Qu.:155.7   1st Qu.: 4.030   Yes:5290  
 Median : 72.70   Median :165.5   Median : 4.680             
 Mean   : 70.99   Mean   :159.9   Mean   : 4.813             
 3rd Qu.: 88.90   3rd Qu.:174.3   3rd Qu.: 5.480             
 Max.   :230.70   Max.   :200.4   Max.   :13.650             </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">nhanes3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Weight           Height         TotChol       PhysActive 
 Min.   :  2.80   Min.   : 83.6   Min.   : 1.530   No  :3677  
 1st Qu.: 56.10   1st Qu.:156.8   1st Qu.: 4.110   Yes :4649  
 Median : 72.70   Median :166.0   Median : 4.780   NA's:1674  
 Mean   : 70.98   Mean   :161.9   Mean   : 4.879              
 3rd Qu.: 88.90   3rd Qu.:174.5   3rd Qu.: 5.530              
 Max.   :230.70   Max.   :200.4   Max.   :13.650              
 NA's   :78       NA's   :353     NA's   :1526                </code></pre>
</div>
</div>
</section></section></section><section id="aykırı-değerler-ile-çalışma" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="aykırı-değerler-ile-çalışma">
<span class="header-section-number">6.2</span> Aykırı Değerler ile Çalışma</h2>
<section id="aykırı-değerlerin-tespiti" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="aykırı-değerlerin-tespiti">
<span class="header-section-number">6.2.1</span> Aykırı Değerlerin Tespiti</h3>
<ul>
<li><p>Kutu grafikleri (<code><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">ggplot2::geom_boxplot()</a></code>).</p></li>
<li><p>Z-skore veya IQR yöntemleri (<code><a href="https://rdrr.io/r/base/scale.html">scale()</a></code>, <code><a href="https://rdrr.io/r/grDevices/boxplot.stats.html">boxplot.stats()</a></code>).</p></li>
</ul></section><section id="aykırı-değerlerin-çıkarılması-veya-düzenlenmesi" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="aykırı-değerlerin-çıkarılması-veya-düzenlenmesi">
<span class="header-section-number">6.2.2</span> Aykırı Değerlerin Çıkarılması veya Düzenlenmesi</h3>
<ul>
<li><p>Veri dönüşümleri ile etkilerini azaltma (ör. <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>, <code><a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a></code>).</p></li>
<li><p>Kategorik aykırılıkların analizi (<code><a href="https://dplyr.tidyverse.org/reference/filter.html">dplyr::filter()</a></code>).</p></li>
</ul></section></section><section id="veri-dönüşümleri-ve-standardizasyon" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="veri-dönüşümleri-ve-standardizasyon">
<span class="header-section-number">6.3</span> Veri Dönüşümleri ve Standardizasyon</h2>
<section id="matematiksel-dönüşümler" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="matematiksel-dönüşümler">
<span class="header-section-number">6.3.1</span> Matematiksel Dönüşümler</h3>
<ul>
<li>Logaritmik (<code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>), karekök (<code><a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a></code>) dönüşümleri</li>
</ul></section><section id="standardizasyon-ve-normalizasyon" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="standardizasyon-ve-normalizasyon">
<span class="header-section-number">6.3.2</span> Standardizasyon ve Normalizasyon</h3>
<pre><code>-   Z-skore standardizasyonu (`scale()`).

-   Min-max normalizasyon (`scales::rescale()`, `caret::preProcess()`).</code></pre>
</section></section><section id="veri-doğrulama-ve-temizleme-işlemleri" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="veri-doğrulama-ve-temizleme-işlemleri">
<span class="header-section-number">6.4</span> Veri Doğrulama ve Temizleme İşlemleri</h2>
<section id="veri-türlerinin-düzenlenmesi" class="level3" data-number="6.4.1"><h3 data-number="6.4.1" class="anchored" data-anchor-id="veri-türlerinin-düzenlenmesi">
<span class="header-section-number">6.4.1</span> Veri Türlerinin Düzenlenmesi</h3>
<section id="kategorik-değişkenler" class="level4" data-number="6.4.1.1"><h4 data-number="6.4.1.1" class="anchored" data-anchor-id="kategorik-değişkenler">
<span class="header-section-number">6.4.1.1</span> Kategorik Değişkenler</h4>
<ul>
<li><p>Kategorilere dönüştürme (<code><a href="https://rdrr.io/r/base/factor.html">as.factor()</a></code>, <code><a href="https://forcats.tidyverse.org/reference/fct_reorder.html">forcats::fct_reorder()</a></code>).</p></li>
<li><p>Seyrek kategorilerin birleştirilmesi (<code><a href="https://forcats.tidyverse.org/reference/fct_lump.html">forcats::fct_lump()</a></code>).</p></li>
</ul></section><section id="tarih-ve-saat-verileri" class="level4" data-number="6.4.1.2"><h4 data-number="6.4.1.2" class="anchored" data-anchor-id="tarih-ve-saat-verileri">
<span class="header-section-number">6.4.1.2</span> Tarih ve Saat Verileri</h4>
<ul>
<li>Tarih dönüşümleri (<code><a href="https://lubridate.tidyverse.org/reference/ymd.html">lubridate::ymd()</a></code>, <code><a href="https://lubridate.tidyverse.org/reference/ymd.html">dmy()</a></code>).</li>
</ul></section><section id="veri-çoğaltmalarının-kaldırılması" class="level4" data-number="6.4.1.3"><h4 data-number="6.4.1.3" class="anchored" data-anchor-id="veri-çoğaltmalarının-kaldırılması">
<span class="header-section-number">6.4.1.3</span> Veri Çoğaltmalarının Kaldırılması</h4>
<ul>
<li>Benzersiz veri seçimi (<code><a href="https://dplyr.tidyverse.org/reference/distinct.html">dplyr::distinct()</a></code>).</li>
</ul>
<p><strong>Referanslar</strong></p>
<p><a href="https://naniar.njtierney.com/" class="uri">https://naniar.njtierney.com/</a></p>
<p><a href="https://www.rdocumentation.org/packages/mice/versions/3.17.0/topics/mice" class="uri">https://www.rdocumentation.org/packages/mice/versions/3.17.0/topics/mice</a></p>
<p><a href="https://choonghyunryu.github.io/dlookr/%20https://rpubs.com/chibueze99/MissingR">https://choonghyunryu.github.io/dlookr/ https://rpubs.com/chibueze99/MissingR</a></p>
<p><a href="https://stefvanbuuren.name/fimd/" class="uri">https://stefvanbuuren.name/fimd/</a></p>
<p><a href="https://rmisstastic.netlify.app/tutorials/josse_bookdown_dataanalysismissingr_2020" class="uri">https://rmisstastic.netlify.app/tutorials/josse_bookdown_dataanalysismissingr_2020</a></p>
<p><a href="https://rpubs.com/rpatel40/handling_missing_data_in_R" class="uri">https://rpubs.com/rpatel40/handling_missing_data_in_R</a></p>
<p><a href="https://www.youtube.com/watch?v=Akb401i32Oc&amp;ab_channel=yuzaRDataScience" class="uri">https://www.youtube.com/watch?v=Akb401i32Oc&amp;ab_channel=yuzaRDataScience</a></p>
<div style="page-break-after: always;"></div>


</section></section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./veri_manipulasyonu.html" class="pagination-link" aria-label="Veri Manipülasyonu">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Veri Manipülasyonu</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="Referanslar">
        <span class="nav-page-text">Referanslar</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>